<?
# INSTRUCTIONS TO TRANSLATORS
#
# This file contains the i18n translations for a subset of the
# Arch Linux User-community Repository (AUR).  This is a PHP
# script, and as such, you MUST pay great attention to the syntax.
# If your text contains any double-quotes ("), you MUST escape
# them with the backslash character (\).
#

include_once("translator.inc");
global $_t;

$_t["en"]["You must supply a password."] = "You must supply a password.";

$_t["en"]["You must supply a username."] = "You must supply a username.";

$_t["en"]["After that, this can be filled in with more meaningful text."] = "After that, this can be filled in with more meaningful text.";

$_t["en"]["Logged-in as: %h%s%h"] = "Logged-in as: %h%s%h";

$_t["en"]["Your account has been suspended."] = "Your account has been suspended.";

$_t["en"]["Password:"] = "Password:";

$_t["en"]["Username:"] = "Username:";

$_t["en"]["Welcome to the AUR! If you're a newcomer, you may want to read the %hGuidelines%h."] = "Welcome to the AUR! If you're a newcomer, you may want to read the %hGuidelines%h.";

$_t["en"]["This is where the intro text will go."] = "This is where the intro text will go.";

$_t["en"]["Error trying to generate session id."] = "Error trying to generate session id.";

$_t["en"]["For now, it's just a place holder."] = "For now, it's just a place holder.";

$_t["en"]["It's more important to get the login functionality finished."] = "It's more important to get the login functionality finished.";

$_t["en"]["Error looking up username, %s."] = "Error looking up username, %s.";

$_t["en"]["Login"] = "Login";

$_t["en"]["Though we can't vouch for their contents, we provide a %hlist of user repositories%h for your convenience."] = "Though we can't vouch for their contents, we provide a %hlist of user repositories%h for your convenience.";

$_t["en"]["If you have feedback about the AUR, please leave it in %hFlyspray%h."] = "If you have feedback about the AUR, please leave it in %hFlyspray%h.";

$_t["en"]["Incorrect password for username, %s."] = "Incorrect password for username, %s.";

$_t["en"]["Latest Packages:"] = "Latest Packages:";

?>