<?
# INSTRUCTIONS TO TRANSLATORS
#
# This file contains the i18n translations for a subset of the
# Arch Linux User-community Repository (AUR).  This is a PHP
# script, and as such, you MUST pay great attention to the syntax.
# If your text contains any double-quotes ("), you MUST escape
# them with the backslash character (\).
#

include_once("translator.inc");
global $_t;

$_t["en"]["Category"] = "Category";

$_t["en"]["Votes"] = "Votes";

$_t["en"]["Comment by: %h%s%h on %h%s%h"] = "Comment by: %h%s%h on %h%s%h";

$_t["en"]["Location"] = "Location";

$_t["en"]["Delete comment"] = "Delete comment";

$_t["en"]["Go"] = "Go";

$_t["en"]["Unflag Out-of-date"] = "Unflag Out-of-date";

$_t["en"]["Go back to %hpackage details view%h."] = "Go back to %hpackage details view%h.";

$_t["en"]["Error retrieving package details."] = "Error retrieving package details.";

$_t["en"]["Description"] = "Description";

$_t["en"]["My Packages"] = "My Packages";

$_t["en"]["Keywords"] = "Keywords";

$_t["en"]["Dependencies"] = "Dependencies";

$_t["en"]["Disown Packages"] = "Disown Packages";

$_t["en"]["Package details could not be found."] = "Package details could not be found.";

$_t["en"]["Package Details"] = "Package Details";

$_t["en"]["Error retrieving package list."] = "Error retrieving package list.";

$_t["en"]["Files"] = "Files";

$_t["en"]["None"] = "None";

$_t["en"]["Name"] = "Name";

$_t["en"]["Per page"] = "Per page";

$_t["en"]["Go back to %hsearch results%h."] = "Go back to %hsearch results%h.";

$_t["en"]["No packages matched your search criteria."] = "No packages matched your search criteria.";

$_t["en"]["O%hrphan"] = "O%hrphan";

$_t["en"]["Un-Vote"] = "Un-Vote";

$_t["en"]["change category"] = "change category";

$_t["en"]["UnNotify"] = "UnNotify";

$_t["en"]["Delete Packages"] = "Delete Packages";

$_t["en"]["Maintainer"] = "Maintainer";

$_t["en"]["Add Comment"] = "Add Comment";

$_t["en"]["Tarball"] = "Tarball";

$_t["en"]["Flag Out-of-date"] = "Flag Out-of-date";

$_t["en"]["Manage"] = "Manage";

$_t["en"]["Sort by"] = "Sort by";

$_t["en"]["Actions"] = "Actions";

$_t["en"]["Sources"] = "Sources";

$_t["en"]["Search Criteria"] = "Search Criteria";

$_t["en"]["Notify"] = "Notify";

$_t["en"]["O%hut-of-Date"] = "O%hut-of-Date";

$_t["en"]["Vote"] = "Vote";

$_t["en"]["Adopt Packages"] = "Adopt Packages";

$_t["en"]["Yes"] = "Yes";

$_t["en"]["Package Listing"] = "Package Listing";

$_t["en"]["Orphans"] = "Orphans";

$_t["en"]["Any"] = "Any";

$_t["en"]["Voted"] = "Voted";

$_t["en"]["No New Comment Notification"] = "No New Comment Notification";

$_t["en"]["New Comment Notification"] = "New Comment Notification";

$_t["en"]["Comments"] = "Comments";

?>