#!/usr/bin/php
<?php
$dir = $argv[1];

if (empty($dir)) {
	echo "Please specify AUR directory.\n";
	exit;
}

set_include_path(get_include_path() . PATH_SEPARATOR . "$dir/lib");
include("config.inc.php");

exec($dir . "/../scripts/aurblup/aurblup " .
	"-S /var/run/mysqld/mysqld.sock " .
	"-u " . escapeshellarg(AUR_db_user) . " " .
	"-p " . escapeshellarg(AUR_db_pass) . " " .
	"-D " . escapeshellarg(AUR_db_name));
