#!/usr/bin/php
<?php
$dir = $argv[1];

if (empty($dir)) {
	echo "Please specify AUR directory.\n";
	exit;
}

set_include_path(get_include_path() . PATH_SEPARATOR . "$dir/lib");
include("confparser.inc.php");

$user = config_get('database', 'user');
$password = config_get('database', 'password');
$name = config_get('database', 'name');

exec($dir . "/../scripts/aurblup/aurblup " .
	"-S /var/run/mysqld/mysqld.sock " .
	"-u " . escapeshellarg($user) . " " .
	"-p " . escapeshellarg($password) . " " .
	"-D " . escapeshellarg($name));
