default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: local
    hooks:
      - id: lint-migrations
        name: lint alembic migrations
        entry: util/lint-migrations
        language: system
        files: ^migrations/
        pass_filenames: false
        stages: [pre-push]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: ^po/
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff-check
      - id: ruff-format
