#!/usr/bin/env python3

from aurweb import config, db, time, util
from aurweb.models import PackageRequest
from aurweb.models.package_request import PENDING_ID, REJECTED_ID
from aurweb.models.request_type import ADOPTION_ID
from aurweb.scripts import notify


def _main() -> list[notify.Notification]:
    now = time.utcnow()
    limit_to = now - config.getint("options", "request_idle_time")

    query = db.query(PackageRequest).filter(
        PackageRequest.ReqTypeID == ADOPTION_ID,
        PackageRequest.Status == PENDING_ID,
        PackageRequest.RequestTS < limit_to,
    )

    notifs = []
    for pkgreq in query:
        pkgreq.Status = REJECTED_ID
        pkgreq.ClosedTS = now
        pkgreq.ClosureComment = (
            f"[Autogenerated] Rejected adoption for {pkgreq.PackageBaseName}: "
            "no Package Maintainer acted on this request in time."
        )
        notifs.append(notify.RequestCloseNotification(0, pkgreq.ID, "rejected"))

    return notifs


def main() -> None:
    db.get_engine()
    with db.begin():
        notifs = _main()

    util.apply_all(notifs, lambda n: n.send())


if __name__ == "__main__":
    main()
