<?
# Italian (Italiano) translation
# Translators: Giovanni Scafora <linuxmania@gmail.com> and Pierluigi Picciau <pierluigi88@gmail.com>

include_once("translator.inc");
global $_t;

$_t["it"]["Use this form to update your account."] = "Usa questo modulo per aggiornare il tuo account.";

$_t["it"]["Leave the password fields blank to keep your same password."] = "Lascia vuoti i campi password per mantenere la stessa password.";

$_t["it"]["You are not allowed to access this area."] = "Non sei autorizzato ad accedere qui.";

$_t["it"]["Could not retrieve information for the specified user."] = "Non ho potuto trovare le informazioni per l'utente specificato.";

$_t["it"]["Use this form to search existing accounts."] = "Usa questo modulo per cercare accounts esistenti.";

$_t["it"]["You do not have permission to edit this account."] = "Non hai il permesso per modificare questo account.";

$_t["it"]["Use this form to create an account."] = "Usa questo modulo per creare un account.";

$_t["it"]["You must log in to view user information."] = "Devi essere autenticato per visualizzare le informazioni dell'utente.";

?>