<?
# Italian (Italiano) translation
# Translators: Giovanni Scafora <linuxmania@gmail.com> and Pierluigi Picciau <pierluigi88@gmail.com>

include_once("translator.inc");
global $_t;

$_t["it"]["Category"] = "Categoria";

$_t["it"]["Votes"] = "Voti";

$_t["it"]["Comment by: %h%s%h on %h%s%h"] = "Commento di: %h%s%h il %h%s%h";

$_t["it"]["Location"] = "Posizione";

$_t["it"]["Delete comment"] = "Elimina il commento";

$_t["it"]["Go"] = "Vai";

$_t["it"]["Unflag Out-of-date"] = "Segna come Aggiornato";

$_t["it"]["Go back to %hpackage details view%h."] = "Torna alla %hvista dettagli del pacchetto%h.";

$_t["it"]["Error retrieving package details."] = "Errore nel recupero dei dettagli del pacchetto.";

$_t["it"]["Description"] = "Descrizione";

$_t["it"]["My Packages"] = "I Miei Pacchetti";

$_t["it"]["Keywords"] = "Parole chiave";

$_t["it"]["Dependencies"] = "Dipendenze";

$_t["it"]["Disown Packages"] = "Abbandona i Pacchetti";

$_t["it"]["Package details could not be found."] = "Impossibile trovare i dettagli del pacchetto.";

$_t["it"]["Package Details"] = "Dettagli del Pacchetto";

$_t["it"]["Error retrieving package list."] = "Errore nel recupero della lista dei pacchetti.";

$_t["it"]["Files"] = "Files";

$_t["it"]["None"] = "Nessuno";

$_t["it"]["Name"] = "Nome";

$_t["it"]["Per page"] = "Per pagina";

$_t["it"]["Go back to %hsearch results%h."] = "Torna ai %hrisulati della ricerca%h.";

$_t["it"]["No packages matched your search criteria."] = "Nessun pacchetto corrisponde ai criteri della tua ricerca.";

$_t["it"]["O%hrphan"] = "O%hrfani";

$_t["it"]["Un-Vote"] = "Rimuovi il Voto";

$_t["it"]["change category"] = "cambia categoria";

$_t["it"]["UnNotify"] = "Togli la Notifica";

$_t["it"]["Delete Packages"] = "Elimina i Pacchetti";

$_t["it"]["Maintainer"] = "Maintainer";

$_t["it"]["Add Comment"] = "Aggiungi un Commento";

$_t["it"]["Tarball"] = "Archivio";

$_t["it"]["Flag Out-of-date"] = "Segna come Non Aggiornato";

$_t["it"]["Manage"] = "Organizza";

$_t["it"]["Sort by"] = "Ordina per";

$_t["it"]["Actions"] = "Azioni";

$_t["it"]["Sources"] = "Sorgenti";

$_t["it"]["Search Criteria"] = "Criteri di Ricerca";

$_t["it"]["Notify"] = "Notifica";

$_t["it"]["O%hut-of-Date"] = "N%hon Aggiornato";

$_t["it"]["Vote"] = "Vota";

$_t["it"]["Adopt Packages"] = "Adotta i Pacchetti";

$_t["it"]["Yes"] = "Si";

$_t["it"]["Package Listing"] = "Lista dei Pacchetti";

$_t["it"]["Orphans"] = "Orfani";

$_t["it"]["Any"] = "Qualsiasi";

$_t["it"]["Voted"] = "Votato";

$_t["it"]["No New Comment Notification"] = "Nessuna Notifica di Nuovo Commento";

$_t["it"]["New Comment Notification"] = "Notifica di Nuovo Commento";

$_t["it"]["Comments"] = "Commenti";

$_t["it"]["The above files have been verified (by %s) and are safe to use."] = "I files sono stati verificati (da %s) ed il loro utilizzo è da considerarsi sicuro.";

$_t["it"]["Be careful! The above files may contain malicious code that can damage your system."] = "Attenzione! I file potrebbero contenere codice pericoloso in grado di danneggiare il tuo sitema.";

$_t["it"]["Flag Safe"] = "Segna come sicuro";

$_t["it"]["Flag Package Safe To Use"] = "Segna il Pacchetto come Sicuro da Utilizzare";

$_t["it"]["Unflag Safe"] = "Segna come Non sicuro";

$_t["it"]["Unflag Package Safe To Use"] = "Segna il Pacchetto come Non Sicuro da Utilizzare";

$_t["it"]["Safe"] = "Sicuro";

$_t["it"]["Age"] = "Data";

$_t["it"]["First Submitted"] = "Primo Invio";

$_t["it"]["Last Updated"] = "Ultimo Aggiornamento";

?>