<?
# Italian (Italiano) translation
# Translators: Giovanni Scafora <linuxmania@gmail.com> and Pierluigi Picciau <pierluigi88@gmail.com>

include_once("translator.inc");
global $_t;

$_t["it"]["Click on the Home link above to log in."] = "Clicca su Inizio per autenticarti.";

$_t["it"]["Your session has timed out.  You must log in again."] = "La tua sessione è scaduta. Devi autenticarti nuovamente.";

?>