<?php
# Italian (Italiano) translation
# Translator: Giovanni Scafora <giovanni@archlinux.org>

include_once("translator.inc");
global $_t;

$_t["it"]["Proposal:"] = "Proposta:";

$_t["it"]["No"] = "No";

$_t["it"]["Username does not exist."] = "Il nome utente non esiste.";

$_t["it"]["Next"] = "Successivo";

$_t["it"]["Add"] = "Aggiungi";

$_t["it"]["Length must be at least 1."] = "La durata deve essere almeno pari ad 1.";

$_t["it"]["(defaults to 7 if empty)"] = "(se vuoto, di default è impostata a 7)";

$_t["it"]["Proposal cannot be empty."] = "La proposta non può essere vuota.";

$_t["it"]["Vote ID not valid."] = "L'ID del voto non è valido.";

$_t["it"]["(empty if not applicable)"] = "(vuoto se non applicabile)";

$_t["it"]["Voting is closed for this proposal."] = "Non puoi più votare per questa proposta.";

$_t["it"]["New proposal submitted."] = "Nuova proposta inviata.";

$_t["it"]["%s already has proposal running for them."] = "%s ha già avviato una proposta per loro.";

$_t["it"]["Length must be a number."] = "La durata deve essere un numero.";

$_t["it"]["You've already voted for this proposal."] = "Hai già votato per questa proposta.";

$_t["it"]["Current Votes"] = "Voti attuali";

$_t["it"]["You've already voted in this proposal."] = "Hai già votato per questa proposta.";

$_t["it"]["You cannot vote in an proposal about you."] = "Non puoi votare per una proposta che ti riguarda in prima persona.";

$_t["it"]["Abstain"] = "Astenuto";

$_t["it"]["You are not allowed to access this area."] = "Non puoi accedere a quest'area.";

$_t["it"]["Length in days:"] = "Durata in giorni:";

$_t["it"]["Back"] = "Indietro";

$_t["it"]["Submit a proposal to vote on."] = "Invia una proposta di voto.";

$_t["it"]["All Votes"] = "Tutti i voti";

$_t["it"]["Could not retrieve proposal details."] = "Impossibile recuperare i dettagli della proposta.";

$_t["it"]["Yes"] = "Sì";

$_t["it"]["Applicant/TU:"] = "Candidato/TU:";

