<?php
# French (Français) translation
# Translator: Morgan LEFIEUX <comete@archlinuxfr.org>
# Translator: Cilyan Olowen <gaknar@gmail.com>

include_once("translator.inc");
global $_t;

$_t["fr"]["Category"] = "Catégorie";

$_t["fr"]["Search by"] = "Rechercher par";

$_t["fr"]["Comments"] = "Commentaires";

$_t["fr"]["orphan"] = "orphelin";

$_t["fr"]["Votes"] = "Votes";

$_t["fr"]["First Submitted"] = "Première soumission";

$_t["fr"]["Tarball"] = "Tarball";

$_t["fr"]["Be careful! The above files may contain malicious code that can damage your system."] = "Attention ! Les fichiers ci-dessus peuvent contenir du code malicieux qui pourrait endommager votre système.";

$_t["fr"]["Voted"] = "Voté";

$_t["fr"]["Location"] = "Dépôt";

$_t["fr"]["Flag Safe"] = "Marquer comme Sain";

$_t["fr"]["Unflag Package Safe To Use"] = "Retirer l'étiquette Sain du paquet";

$_t["fr"]["Unflag Out-of-date"] = "Retirer l'étiquette Périmé";

$_t["fr"]["Go back to %hpackage details view%h."] = "Retourner à la %hvue des détails du paquet%h.";

$_t["fr"]["Error retrieving package details."] = "Erreur en recherchant les détails du paquet.";

$_t["fr"]["Leave the password fields blank to keep your same password."] = "Laissez les champs du mot de passe vides pour conserver le même mot de passe.";

$_t["fr"]["Description"] = "Description";

$_t["fr"]["My Packages"] = "Mes paquets";

$_t["fr"]["Safe"] = "Sain";

$_t["fr"]["You have been successfully logged out."] = "Vous avez été déconnecté avec succès.";

$_t["fr"]["Ascending"] = "Ascendant";

$_t["fr"]["Delete comment"] = "Effacer le commentaire";

$_t["fr"]["No New Comment Notification"] = "Pas d'annonce de nouveau commentaire";

$_t["fr"]["Dependencies"] = "Dépendances";

$_t["fr"]["Descending"] = "Descendant";

$_t["fr"]["Per page"] = "Par page";

$_t["fr"]["Package Listing"] = "Liste des Paquets";

$_t["fr"]["Package details could not be found."] = "Les détails du paquet ne peuvent pas être trouvés.";

$_t["fr"]["You must log in to view user information."] = "Vous devez vous authentifier pour voir les informations de l'utilisateur.";

$_t["fr"]["Package Details"] = "Détails du Paquet";

$_t["fr"]["Error retrieving package list."] = "Erreur en recherchant la liste des paquets.";

$_t["fr"]["Files"] = "Fichiers";

$_t["fr"]["Name"] = "Nom";

$_t["fr"]["Last Updated"] = "Dernière mise à jour";

$_t["fr"]["The above files have been verified (by %s) and are safe to use."] = "Les fichiers ci-dessus ont été vérifiés (par %s) et sont sains.";

$_t["fr"]["Could not retrieve information for the specified user."] = "Impossible de retrouver l'information pour l'utilisateur spécifié.";

$_t["fr"]["UnNotify"] = "Ne plus annoncer";

$_t["fr"]["You do not have permission to edit this account."] = "Vous n'avez pas la permission d'éditer ce compte.";

$_t["fr"]["Keywords"] = "Mots clés";

$_t["fr"]["Age"] = "Age";

$_t["fr"]["Use this form to search existing accounts."] = "Utilisez ce formulaire pour rechercher des comptes existants.";

$_t["fr"]["Submitter"] = "Contributeur";

$_t["fr"]["Use this form to create an account."] = "Utilisez ce formulaire pour créer un compte.";

$_t["fr"]["Un-Vote"] = "Retirer mon vote";

$_t["fr"]["change category"] = "changer de catégorie";

$_t["fr"]["Vote"] = "Voter";

$_t["fr"]["Use this form to update your account."] = "Utilisez ce formulaire pour mettre à jour votre compte.";

$_t["fr"]["Delete Packages"] = "Supprimer des Paquets";

$_t["fr"]["Maintainer"] = "Mainteneur";

$_t["fr"]["Add Comment"] = "Ajouter un Commentaire";

$_t["fr"]["Comment by: %h%s%h on %h%s%h"] = "Commenté par: %h%s%h sur %h%s%h";

$_t["fr"]["Flag Out-of-date"] = "Marquer comme Périmé";

$_t["fr"]["You are not allowed to access this area."] = "Vous n'avez pas la permission d'accéder à cet espace.";

$_t["fr"]["Manage"] = "Gérer";

$_t["fr"]["Sort by"] = "Trier par";

$_t["fr"]["Flag Package Safe To Use"] = "Marquer le paquet comme Sain";

$_t["fr"]["Actions"] = "Actions";

$_t["fr"]["Unflag Safe"] = "Retirer l'étiquette Sain";

$_t["fr"]["Disown Packages"] = "Abandonner les paquets";

$_t["fr"]["Sources"] = "Sources";

$_t["fr"]["Yes"] = "Oui";

$_t["fr"]["Search Criteria"] = "Critères de recherche";

$_t["fr"]["Notify"] = "Annoncer";

$_t["fr"]["Go"] = "Aller";

$_t["fr"]["O%hut-of-Date"] = "P%hérimé";

$_t["fr"]["Go back to %hsearch results%h."] = "Retourner aux %hrésultats de la recherche%h.";

$_t["fr"]["Adopt Packages"] = "Adopter des paquets";

$_t["fr"]["New Comment Notification"] = "Annonce de nouveau commentaire";

$_t["fr"]["Sort order"] = "Ordre de tri";

$_t["fr"]["Orphans"] = "Orphelins";

$_t["fr"]["Any"] = "Tous";

$_t["fr"]["No packages matched your search criteria."] = "Aucun paquet ne correspond à vos critères de recherche.";

$_t["fr"]["Status"] = "Etat";

$_t["fr"]["License"] = "Licence";

$_t["fr"]["All"] = "Tout";

$_t["fr"]["Unsafe"] = "Non sûr";

$_t["fr"]["unknown"] = "inconnu";

$_t["fr"]["Showing results %s - %s of %s"] = "Résultats %s à %s pour un total de %s";

$_t["fr"]["Out of Date"] = "Périmé";

$_t["fr"]["Required by"] = "Requis par";

$_t["fr"]["This package has been flagged out of date."] = "Ce paquet a été marqué comme périmé.";

$_t["fr"]["Toggle Notify"] = "Annoncer/Ne plus annoncer";

$_t["fr"]["Accounts"] = "Comptes";

$_t["fr"]["Couldn't add to notification list."] = "Impossible d'ajouter aux notifications.";

$_t["fr"]["You must be logged in before you can flag packages."] = "Vous devez vous identifier avant de pouvoir marquer un paquet.";

$_t["fr"]["Your votes have been removed from the selected packages."] = "Vos votes ont été retirés des paquets sélectionnés.";

$_t["fr"]["The selected packages have been disowned."] = "Les paquets sélectionnés ont été abandonnés.";

$_t["fr"]["None of the selected packages could be deleted."] = "Aucun des paquets sélectionnés n'a pu être effacé.";

$_t["fr"]["The selected packages have been unflagged."] = "La marque a été retirée des paquets sélectionnés.";

$_t["fr"]["You must be logged in before you can unflag packages."] = "Vous devez vous identifier pour retirer la marque d'un paquet.";

$_t["fr"]["You did not select any packages to adopt."] = "Vous n'avez pas sélectionné de paquet à adopter.";

$_t["fr"]["You must be logged in before you can get notifications on comments."] = "Vous devez vous identifier avant de pouvoir recevoir des notifications de commentaires.";

$_t["fr"]["The selected packages have been flagged out-of-date."] = "Les paquets sélectionnés ont été marqués comme périmés.";

$_t["fr"]["The selected packages have been deleted."] = "Les paquets sélectionnés ont été supprimés.";

$_t["fr"]["You did not select any packages to vote for."] = "Vous n'avez pas sélectionné de paquet pour lesquels voter.";

$_t["fr"]["You must be logged in before you can disown packages."] = "Vous devez vous identifier avant de pouvoir abandonner des paquets.";

$_t["fr"]["The selected packages have been adopted."] = "Les paquets sélectionnés ont été adoptés.";

$_t["fr"]["You must be logged in before you can adopt packages."] = "Vous devez vous identifier avant de pouvoir adopter des paquets.";

$_t["fr"]["You must be logged in before you can vote for packages."] = "Vous devez vous identifier avant de pouvoir voter pour des paquets.";

$_t["fr"]["You did not select any packages to disown."] = "Vous n'avez pas sélectionné de paquet à abandonner.";

$_t["fr"]["You must be logged in before you can un-vote for packages."] = "Vous devez vous identifier avant de pouvoir retirer vos votes sur des paquets";

$_t["fr"]["You did not select any packages to unflag."] = "Vous n'avez sélectionné aucun paquet duquel retirer la marque.";

$_t["fr"]["You did not select any packages to delete."] = "Vous n'avez sélectionné aucun paquet à supprimer.";

$_t["fr"]["You have been removed from the comment notification list for %s."] = "Vous avez été supprimé de la liste des notifications de commentaire pour %s.";

$_t["fr"]["Your votes have been cast for the selected packages."] = "Vos votes ont été ajoutés aux paquets sélectionnés.";

$_t["fr"]["You did not select any packages to flag."] = "Vous n'avez sélectionné aucun paquet à marquer.";

$_t["fr"]["Home"] = "Accueil";

$_t["fr"]["You have been added to the comment notification list for %s."] = "Vous avez été ajouté à la liste des notifications de commentaire pour %s.";

