<?php
# French (Français) translation
# Translator: Cilyan Olowen <gaknar@gmail.com>

include_once("translator.inc");
global $_t;

$_t["fr"]["Proposal:"] = "Proposition :";

$_t["fr"]["No"] = "Non";

$_t["fr"]["Username does not exist."] = "Le nom d'utilisateur n'existe pas.";

$_t["fr"]["Next"] = "Suivant";

$_t["fr"]["Add"] = "Ajouter";

$_t["fr"]["Length must be at least 1."] = "La durée doit être au moins de 1.";

$_t["fr"]["(defaults to 7 if empty)"] = "(7 par défaut si laissé vide)";

$_t["fr"]["Proposal cannot be empty."] = "Une proposition ne peut être vide.";

$_t["fr"]["Vote ID not valid."] = "ID de vote non valide.";

$_t["fr"]["(empty if not applicable)"] = "(vide si non applicable)";

$_t["fr"]["Voting is closed for this proposal."] = "Le vote est clos pour cette proposition.";

$_t["fr"]["New proposal submitted."] = "Nouvelle proposition enregistrée.";

$_t["fr"]["%s already has proposal running for them."] = "%s a déjà une proposition en cours à son sujet.";

$_t["fr"]["Length must be a number."] = "La durée doit être un nombre.";

$_t["fr"]["You've already voted for this proposal."] = "Vous avez déjà voté pour cette proposition.";

$_t["fr"]["Current Votes"] = "Votes en cours";

$_t["fr"]["You've already voted in this proposal."] = "Vous avez déjà voté pour cette proposition.";

$_t["fr"]["You cannot vote in an proposal about you."] = "Vous ne pouvez pas voter dans une proposition à votre sujet.";

$_t["fr"]["Abstain"] = "Abstention";

$_t["fr"]["You are not allowed to access this area."] = "Vous n'avez pas la permission d'accéder à cet espace.";

$_t["fr"]["Length in days:"] = "Durée en jours :";

$_t["fr"]["Back"] = "Retour";

$_t["fr"]["Submit a proposal to vote on."] = "Soumettre une proposition à laquelle voter.";

$_t["fr"]["All Votes"] = "Tous les votes";

$_t["fr"]["Could not retrieve proposal details."] = "Impossible d'obtenir le détail de la proposition.";

$_t["fr"]["Yes"] = "Oui";

$_t["fr"]["Applicant/TU:"] = "Postulant/TU :";

