<?php
# INSTRUCTIONS TO TRANSLATORS
#
# This file contains the i18n translations for a subset of the
# Arch Linux User-community Repository (AUR).  This is a PHP
# script, and as such, you MUST pay great attention to the syntax.
# If your text contains any double-quotes ("), you MUST escape
# them with the backslash character (\).
#

include_once("translator.inc");
global $_t;

$_t["tr"]["Use this form to update your account."] = "Hesap bilgilerinizi güncellemek için bu formu kullanın.";

$_t["tr"]["Leave the password fields blank to keep your same password."] = "Şifrenizi değiştirmek istemiyorsanız şifre kısmını boş bırakın.";

$_t["tr"]["You are not allowed to access this area."] = "Bu kısma erişim izniniz yok.";

$_t["tr"]["Could not retrieve information for the specified user."] = "Kullanıcı verileri alınamadı.";

$_t["tr"]["Use this form to search existing accounts."] = "Mevcut hesaplar içinde arama yapmak için bu formu kullanın.";

$_t["tr"]["You do not have permission to edit this account."] = "Bu hesap üzerinde değişiklik yapma izniniz yok.";

$_t["tr"]["Use this form to create an account."] = "Yeni bir hesap oluşturmak için bu formu kullanın.";

$_t["tr"]["You must log in to view user information."] = "Kullanıcı bilgilerini görmek için giriş yapmalısınız.";

