<?php
# INSTRUCTIONS TO TRANSLATORS
#
# This file contains the i18n translations for a subset of the
# Arch Linux User-community Repository (AUR).  This is a PHP
# script, and as such, you MUST pay great attention to the syntax.
# If your text contains any double-quotes ("), you MUST escape
# them with the backslash character (\).
#

include_once("translator.inc");
global $_t;

$_t["tr"]["Missing a required field."] = "Gerekli bir alan doldurulmamış.";

$_t["tr"]["Search"] = "Ara";

$_t["tr"]["The account, %h%s%h, has been successfully created."] = "Hesap %h%s%h başarıyla oluşturuldu.";

$_t["tr"]["Error trying to modify account, %h%s%h: %s."] = "Hesap %h%s%h düzenlenirken hata oluştu.";

$_t["tr"]["The email address is invalid."] = "Eposta adresi geçerli dğeil.";

$_t["tr"]["Error trying to create account, %h%s%h: %s."] = "Hesap %h%s%h oluşturulurken hata oluştu: %s.";

$_t["tr"]["The username, %h%s%h, is already in use."] = "%h%s%h kullanıcı adı kullanımda.";

$_t["tr"]["Account Type"] = "Hesap Türü";

$_t["tr"]["The account, %h%s%h, has been successfully modified."] = "Hesap %h%s%h başarıyla düzenlendi.";

$_t["tr"]["Account Suspended"] = "Hesap Donduruldu";

$_t["tr"]["Status"] = "Durum";

$_t["tr"]["New Package Notify"] = "Yeni Paket Bildirimi";

$_t["tr"]["IRC Nick"] = "IRC Nick";

$_t["tr"]["Trusted user"] = "Güvenilen kullanıcı";

$_t["tr"]["No results matched your search criteria."] = "Uygun sonuç bulunamadı.";

$_t["tr"]["Normal user"] = "Normal kullanıcı";

$_t["tr"]["Never"] = "Hiç";

$_t["tr"]["User"] = "Kullanıcı";

$_t["tr"]["Active"] = "Aktif";

$_t["tr"]["Last Voted"] = "Son Oylanan";

$_t["tr"]["Real Name"] = "Gerçek İsim";

$_t["tr"]["Edit Account"] = "Hesap Bilgilerini Düzenle";

$_t["tr"]["Password fields do not match."] = "Şifreler birbirinin aynı değil.";

$_t["tr"]["Language"] = "Dil";

$_t["tr"]["A Trusted User cannot assign Developer status."] = "Güvenilen Kullanıcı Geliştirici durumu belirleyemez.";

$_t["tr"]["The address, %h%s%h, is already in use."] = "%h%s%h adresi kullanımda.";

$_t["tr"]["No more results to display."] = "Gösterilecek daha fazla sonuç yok.";

$_t["tr"]["Type"] = "Tür";

$_t["tr"]["Click on the Home link above to login."] = "Giriş yapmak için aşağıdaki Ev bağlantısını tıklayın..";

$_t["tr"]["Sort by"] = "Sıralama kriteri";

$_t["tr"]["Re-type password"] = "Şifreyi tekrarlayın";

$_t["tr"]["Language is not currently supported."] = "Dil henüz desteklenmiyor.";

$_t["tr"]["Any type"] = "Herhangi bir tür";

$_t["tr"]["Last vote"] = "Last vote";

$_t["tr"]["Suspended"] = "Donduruldu";

$_t["tr"]["Trusted User"] = "Güvenilen Kullanıcı";

$_t["tr"]["Missing User ID"] = "Kullanıcı kimliği eksik";

$_t["tr"]["Developer"] = "Geliştirici";

$_t["tr"]["View this user's packages"] = "Bu kullanıcı tarafından hazırlanan paketleri göster";

