<?php
# INSTRUCTIONS TO TRANSLATORS
#
# This file contains the i18n translations for a subset of the
# Arch Linux User-community Repository (AUR).  This is a PHP
# script, and as such, you MUST pay great attention to the syntax.
# If your text contains any double-quotes ("), you MUST escape
# them with the backslash character (\).
#

include_once("translator.inc");
global $_t;

$_t["tr"]["Home"] = "Anasayfa";

$_t["tr"]["%s: An ArchLinux project"] = "%s: Bir ArchLinux projesi";

$_t["tr"]["Packages"] = "Paketler";

$_t["tr"]["Accounts"] = "Hesabım";

$_t["tr"]["Logout"] = "Çıkış";

$_t["tr"]["%s: %sAn ArchLinux project%s"] = "%s: %sBir ArchLinux projesi%s";

$_t["tr"]["Discussion"] = "Tartışma";

$_t["tr"]["Bugs"] = "Hatalar";

$_t["tr"]["Trusted User"] = "Güvenilen Kullanıcı";

