<?php
# INSTRUCTIONS TO TRANSLATORS
#
# This file contains the i18n translations for a subset of the
# Arch Linux User-community Repository (AUR).  This is a PHP
# script, and as such, you MUST pay great attention to the syntax.
# If your text contains any double-quotes ("), you MUST escape
# them with the backslash character (\).
#

include_once("translator.inc");
global $_t;

$_t["tr"]["Reset"] = "Sıfırla";

$_t["tr"]["Username"] = "Kullanıcı Adı";

$_t["tr"]["Email Address"] = "Eposta adresi";

$_t["tr"]["Less"] = "Önceki";

$_t["tr"]["Clear"] = "Temizle";

$_t["tr"]["required"] = "gerekli";

$_t["tr"]["Update"] = "Güncelle";

$_t["tr"]["Submit"] = "Gönder";

$_t["tr"]["Password"] = "Şifre";

$_t["tr"]["Create"] = "Oluştur";

$_t["tr"]["More"] = "Sonraki";

