<?php
# INSTRUCTIONS TO TRANSLATORS
#
# This file contains the i18n translations for a subset of the
# Arch Linux User-community Repository (AUR).  This is a PHP
# script, and as such, you MUST pay great attention to the syntax.
# If your text contains any double-quotes ("), you MUST escape
# them with the backslash character (\).
#

include_once("translator.inc");
global $_t;

$_t["tr"]["You must supply a password."] = "Bir parola belirlemelisiniz.";

$_t["tr"]["You must supply a username."] = "Bir kullanıcı adı belirlemelisiniz.";

$_t["tr"]["After that, this can be filled in with more meaningful text."] = "Eksiklikleri tamamladıktan sonra, bu kısma anlamlı bir açıklama yazabilirsiniz.";

$_t["tr"]["Logged-in as: %h%s%h"] = "%h%s%h olarak giriş yapıldı";

$_t["tr"]["Your account has been suspended."] = "Hesabınız donduruldu.";

$_t["tr"]["Password:"] = "Şifre:";

$_t["tr"]["Username:"] = "Kullanıcı Adı:";

$_t["tr"]["Welcome to the AUR! If you're a newcomer, you may want to read the %hGuidelines%h."] = "AUR'a hoş geldiniz! Yeni katıldıysanız, belki de  %hKılavuz%h 'a bir göz atmak istersiniz.";

$_t["tr"]["This is where the intro text will go."] = "Tanıtım yazısının gösterileceği kısımdır.";

$_t["tr"]["Error trying to generate session id."] = "Oturum kimliği oluşturulmaya çalışılırken hata oluştu.";

$_t["tr"]["For now, it's just a place holder."] = "Şimdilik bu kısım sadece yer işgal etmektedir.";

$_t["tr"]["It's more important to get the login functionality finished."] = "Giriş işlemi fonksiyonunun tamamlanması daha fazla önem arz etmektedir.";

$_t["tr"]["Login"] = "Giriş";

$_t["tr"]["Though we can't vouch for their contents, we provide a %hlist of user repositories%h for your convenience."] = "İçeriklerine kefil olmasak da, kullanmanız için %hkullanıcı deposu listesi%h sağlamaktayız. ";

$_t["tr"]["If you have feedback about the AUR, please leave it in %hFlyspray%h."] = "AUR ile ilgili geribildirim yapmak için lütfen %hFlyspray%h 'i kullanın.";

$_t["tr"]["Latest Packages:"] = "Son paketler:";

$_t["tr"]["Discussion about the AUR takes place on the %sTUR Users List%s."] = "AUR ile ilgili tartışmalar %sTUR Kullanıcı Listesi%s 'nde.";

$_t["tr"]["Email discussion about the AUR takes place on the %sTUR Users List%s."] = "AUR hakkındaki e-posta tartışmaları %sTUR Eposta Listesi%s üzerinde gerçekleşmektedir.";

$_t["tr"]["Recent Updates"] = "Son Güncellemeler";

$_t["tr"]["Community"] = "Topluluk";

$_t["tr"]["Package Counts"] = "Paket Sayıları";

$_t["tr"]["Welcome to the AUR! Please read the %hAUR User Guidelines%h and %hAUR TU Guidelines%h for more information."] = "AUR'a hoşgeldiniz! Ayrıntılı bilgi için lütfen %hAUR Kullanıcı Kılavuzu%h ve %hAUR GK Kılavuzu%hnu okuyun.";

$_t["tr"]["Unsupported"] = "Desteklenmiyor";

$_t["tr"]["Contributed PKGBUILDs %hmust%h conform to the %hArch Packaging Standards%h otherwise they will be deleted!"] = "Eklenen PKGBUILD dosyaları %hArch Paket Standartları%hna %huymalıdır%h aksi takdirde silinecektir!";

$_t["tr"]["Statistics"] = "İstatistikler";

$_t["tr"]["My Statistics"] = "İstatistiklerim";

$_t["tr"]["Flagged as safe by me"] = "Tarafımdan güvenli olarak işaretlenmiş";

$_t["tr"]["Flagged as safe"] = "Güvenli olarak işaretmiş";

$_t["tr"]["User Statistics"] = "Kullanıcı İstatistikleri";

$_t["tr"]["Registered Users"] = "Kayıtlı Kullanıcılar";

$_t["tr"]["Trusted Users"] = "Güvenilen Kullanıcılar";

$_t["tr"]["Packages in unsupported"] = "Desteklenmeyen paketler";

$_t["tr"]["Packages in unsupported and flagged as safe"] = "Desteklenmeyen ve güvenli olarak olarak işaretlenen paketler";

$_t["tr"]["Packages in [community]"] = "[community] üzerindeki paketler";

$_t["tr"]["Remember to vote for your favourite packages!"] = "Beğendiğiniz paketleri oylamayı unutmayın!";

$_t["tr"]["Packages added or updated in the past 7 days"] = "Son 7 günde eklenen ya da güncellenen paketler";

$_t["tr"]["Out-of-date"] = "Güncelliğini yitirmiş";

$_t["tr"]["DISCLAIMER"] = "FERAGATNAME";

$_t["tr"]["Login failure: Bad user or pass."] = "Giriş hatası: Hatalı kullanıcı adı veya parola";

$_t["tr"]["Some packages may be provided as binaries in [community]."] = "Burada listelenen paketlerin bazıları [community] deposunda yer almaktadır.";

$_t["tr"]["Unsupported packages are user produced content. Any use of the provided files is at your own risk."] = "Desteklenmeyen paketler kullanıcının kendi ürettiği içeriğidir. Bu paketlerin kullanımından doğan risk kullanıcının kendisine aittir."; 
