<?php
# INSTRUCTIONS TO TRANSLATORS
#
# This file contains the i18n translations for a subset of the
# Arch Linux User-community Repository (AUR).  This is a PHP
# script, and as such, you MUST pay great attention to the syntax.
# If your text contains any double-quotes ("), you MUST escape
# them with the backslash character (\).
#

include_once("translator.inc");
global $_t;

$_t["tr"]["Missing package ID."] = "Paket kimliği bulunamadı.";

$_t["tr"]["Invalid category ID."] = "Geçersiz kategori.";

$_t["tr"]["Enter your comment below."] = "Lütfen yorumunuzu yazınız.";

$_t["tr"]["You are not allowed to delete this comment."] = "Bu yorumu silme yetkiniz yok.";

$_t["tr"]["Missing comment ID."] = "Yorum kimliği bulunamadı.";

$_t["tr"]["Package category updated."] = "Paket kategorisi güncellendi.";

$_t["tr"]["You must be logged in before you can edit package information."] = "Paket bilgilerini güncellemek için giriş yapmalısınız.";

$_t["tr"]["Comment has been deleted."] = "Yorum silindi.";

$_t["tr"]["You've found a bug if you see this...."] = "Bu yazıyı görebiliyorsanız bir hata keşfettiniz";

$_t["tr"]["Comment has been added."] = "Yorum eklendi.";

$_t["tr"]["Select new category"] = "Yeni kategori seçin";

