<?php
# INSTRUCTIONS TO TRANSLATORS
#
# This file contains the i18n translations for a subset of the
# Arch Linux User-community Repository (AUR).  This is a PHP
# script, and as such, you MUST pay great attention to the syntax.
# If your text contains any double-quotes ("), you MUST escape
# them with the backslash character (\).
#

include_once("translator.inc");
global $_t;

$_t["tr"]["Category"] = "Kategori";

$_t["tr"]["Votes"] = "Oy";

$_t["tr"]["Comment by: %h%s%h on %h%s%h"] = "Yorum sahibi: %h%s%h on %h%s%h";

$_t["tr"]["Location"] = "Yer";

$_t["tr"]["Delete comment"] = "Yorumu sil";

$_t["tr"]["Go"] = "Git";

$_t["tr"]["Unflag Out-of-date"] = "Güncel Değil İşaretini Kaldır";

$_t["tr"]["Go back to %hpackage details view%h."] = "Go back to %hpackage details view%h.";

$_t["tr"]["Error retrieving package details."] = "Paket bilgileri alınırken hata oluştu.";

$_t["tr"]["Description"] = "Açıklama";

$_t["tr"]["My Packages"] = "Paketlerim";

$_t["tr"]["Keywords"] = "Anahtar kelimeler";

$_t["tr"]["Dependencies"] = "Bağımlılıklar";

$_t["tr"]["Disown Packages"] = "Paketleri sahiplenmeyi bırak";

$_t["tr"]["Package details could not be found."] = "Paket ayrıntıları bulunamadı.";

$_t["tr"]["Package Details"] = "Paket Ayrıntıları";

$_t["tr"]["Error retrieving package list."] = "Paket listesi alınırken hata oluştu.";

$_t["tr"]["Files"] = "Dosyalar";

$_t["tr"]["None"] = "None";

$_t["tr"]["Name"] = "Name";

$_t["tr"]["Per page"] = "Her sayfa";

$_t["tr"]["Go back to %hsearch results%h."] = "%hArama sonuçları%h'na dön.";

$_t["tr"]["No packages matched your search criteria."] = "Eşleşen paket bulunamadı.";

$_t["tr"]["O%hrphan"] = "";

$_t["tr"]["orphan"] = "sahipsiz";

$_t["tr"]["Un-Vote"] = "";

$_t["tr"]["change category"] = "kategori değiştir";

$_t["tr"]["UnNotify"] = "";

$_t["tr"]["Delete Packages"] = "Paketleri Sil";

$_t["tr"]["Maintainer"] = "Destekçi";

$_t["tr"]["Add Comment"] = "Yorum Ekle";

$_t["tr"]["Tarball"] = "Tarball";

$_t["tr"]["Flag Out-of-date"] = "Güncelliğini yitirmiş olarak işaretle";

$_t["tr"]["Manage"] = "Yönet";

$_t["tr"]["Sort by"] = "";

$_t["tr"]["Sort order"] = "Sıralama kriteri";

$_t["tr"]["Ascending"] = "Artan";

$_t["tr"]["Descending"] = "Azalan";

$_t["tr"]["Actions"] = "Eylemler";

$_t["tr"]["Sources"] = "Kaynaklar";

$_t["tr"]["Search Criteria"] = "Arama Kriteri";

$_t["tr"]["Notify"] = "Bilgilendir";

$_t["tr"]["Out of Date"] = "Güncel Değil";

$_t["tr"]["Vote"] = "Oy ver";

$_t["tr"]["Adopt Packages"] = "Paketleri Sahiplen";

$_t["tr"]["Yes"] = "Evet";

$_t["tr"]["Package Listing"] = "Paket Listeleme";

$_t["tr"]["Orphans"] = "Sahipsiz";

$_t["tr"]["Any"] = "Tümü";

$_t["tr"]["Voted"] = "Oylanan";

$_t["tr"]["No New Comment Notification"] = "Yeni Yorum Bildirim Yok";

$_t["tr"]["New Comment Notification"] = "Yeni Yorum Bildirimi";

$_t["tr"]["Comments"] = "Yorumlar";

$_t["tr"]["The above files have been verified (by %s) and are safe to use."] = "Yukarıdaki dosyalar doğrulandı (by %s) ve güvenli olarak işaretlendi.";

$_t["tr"]["Be careful! The above files may contain malicious code that can damage your system."] = "Dikkat! Yukarıdaki dosyalar sisteminize zarar verebilecek nitelikte olabilir.";

$_t["tr"]["Flag Safe"] = "Güvenli Olarak İşaretle";

$_t["tr"]["Flag Package Safe To Use"] = "Paketi Güvenli Olarak İşaretle";

$_t["tr"]["Unflag Safe"] = "Güvenilirlik İşaretini Kaldır";

$_t["tr"]["Unflag Package Safe To Use"] = "Paketin Güvenilirlik İşaretini Kaldır";

$_t["tr"]["Safe"] = "Güvenli";

$_t["tr"]["Age"] = "Yaş";

$_t["tr"]["First Submitted"] = "İlk Gönderim";

$_t["tr"]["Last Updated"] = "Son Güncelleme";

$_t["tr"]["Search by"] = "";

$_t["tr"]["Submitter"] = "Gönderen";

$_t["tr"]["All"] = "Tümü";

$_t["tr"]["Unsafe"] = "Güvensiz";

$_t["tr"]["Status"] = "Durum";

$_t["tr"]["License"] = "Lisans";

$_t["tr"]["unknown"] = "bilinmiyor";

$_t["tr"]["Required by"] = "";

$_t["tr"]["The above files have been verified (by %h%s%h) and are safe to use."] = "The above files have been verified (by %h%s%h) and are safe to use.";

$_t["tr"]["This package has been flagged out of date."] = "Bu paket 'güncel değil' olarak işaretlendi.";

$_t["tr"]["Toggle Notify"] = "Toggle Notify";

$_t["tr"]["Showing results %s - %s of %s"] = "%s - %s görüntüleniyor, %s sonuç arasından";

