<?php
# INSTRUCTIONS TO TRANSLATORS
#
# This file contains the i18n translations for a subset of the
# Arch Linux User-community Repository (AUR).  This is a PHP
# script, and as such, you MUST pay great attention to the syntax.
# If your text contains any double-quotes ("), you MUST escape
# them with the backslash character (\).
#
include_once("translator.inc");
global $_t;

$_t["tr"]["None of the selected packages could be deleted."] = "Seçilen paketlerin hiçbiri silinemedi.";

$_t["tr"]["Your votes have been removed from the selected packages."] = "Seçtiğiniz paketlerden oyunuz geri alındı.";

$_t["tr"]["You did not select any packages to un-vote for."] = "Oyunuzu geri almak üzere paket seçmediniz.";

$_t["tr"]["The selected packages have been unflagged."] = "Seçilen paketlerin işareti kaldırıldı.";

$_t["tr"]["You did not select any packages to adopt."] = "Sahiplenilecek paket(ler)i seçmediniz.";

$_t["tr"]["You must be logged in before you can flag packages."] = "Paketleri işaretleyebilmek için giriş yapmalısınız.";

$_t["tr"]["You must be logged in before you can get notifications on comments."] = "Yorum bildirisi almak için giriş yapmalısınız.";

$_t["tr"]["You must be logged in before you can vote for packages."] = "Paketlere oy vermeden önce giriş yapmalısınız.";

$_t["tr"]["The selected packages have been flagged out-of-date."] = "Seçilen paketler güncelliğini yitirmiş olarak işaretlendi.";

$_t["tr"]["The selected packages have been deleted."] = "Seçilen paketler silindi.";

$_t["tr"]["You did not select any packages to vote for."] = "Oy verilecek paketleri seçmediniz.";

$_t["tr"]["You must be logged in before you can disown packages."] = "Paketlerin sahipliğini bırakmak için giriş yapmalısınız.";

$_t["tr"]["Error trying to retrieve package details."] = "Paket ayrıntılarını almaya çalışırken hata oluştu.";

$_t["tr"]["The selected packages have been adopted."] = "Seçilen paketler sahiplenildi.";

$_t["tr"]["You have been removed from the comment notification list for %s."] = "%s bildirim listesinden başarıyla çıktınız.";

$_t["tr"]["Your votes have been cast for the selected packages."] = "Seçtiğiniz paketlere oyunuz eklendi.";

$_t["tr"]["You must be logged in before you can cancel notification on comments."] = "Yorum bildirimlerini iptal etmek için giriş yapmalısınız.";

$_t["tr"]["You must be logged in before you can adopt packages."] = "Paketleri sahiplenmek için giriş yapmalısınız.";

$_t["tr"]["You have been added to the comment notification list for %s."] = "%s bildirim listesine başarıyla eklendiniz.";

$_t["tr"]["You did not select any packages to disown."] = "Sahipliği bırakılacak paketleri seçmediniz.";

$_t["tr"]["You must be logged in before you can un-vote for packages."] = "Oy iptali için giriş yapmalısınız.";

$_t["tr"]["You must be logged in before you can unflag packages."] = "Paket(ler)in işaretini kaldırabilmek için giriş yapmalısınız.";

$_t["tr"]["You did not select any packages to unflag."] = "İşareti kaldırılacak paket(ler)i seçmediniz.";

$_t["tr"]["You did not select any packages to delete."] = "Silinecek paketleri seçmediniz.";

$_t["tr"]["Couldn't add to notification list."] = "Bildirim listesine ekleme işlemi başarısız oldu.";

$_t["tr"]["You did not select any packages to flag."] = "İşaretlenecek paket(ler)i seçmediniz.";

$_t["tr"]["The selected packages have been disowned."] = "Seçilen paketlerin sahipliği bırakıldı.";

$_t["tr"]["Couldn't remove from notification list."] = "Bildirim listesinden silme işlemi başarısız oldu.";

$_t["tr"]["The selected packages have been flagged safe."] = "Seçilen paketler güvenli olarak işaretlendi";

$_t["tr"]["Couldn't flag package safe."] = "Paket güvenli olarak işaretlenemedi.";

$_t["tr"]["The selected packages have been unflagged safe."] = "Seçilen paketler artık güvenli olarak işaretli değil.";

$_t["tr"]["Couldn't unflag package safe."] = "Güvenli işaretini kaldırma işlemi başarısız oldu.";

