<?php
# INSTRUCTIONS TO TRANSLATORS
#
# This file contains the i18n translations for a subset of the
# Arch Linux User-community Repository (AUR).  This is a PHP
# script, and as such, you MUST pay great attention to the syntax.
# If your text contains any double-quotes ("), you MUST escape
# them with the backslash character (\).
#

include_once("translator.inc");
global $_t;

$_t["tr"]["Missing build function in PKGBUILD."] = "PKGBUILD içinde build fonksiyonu bulunmadı.";

$_t["tr"]["Could not change directory to %s."] = "%s dizinine geçilemedi.";

$_t["tr"]["No"] = "Hayır";

$_t["tr"]["Missing pkgdesc variable in PKGBUILD."] = "PKGBUILD içinde pkgdesc değişkeni bulunamadı.";

$_t["tr"]["Error trying to upload file - please try again."] = "Dosya yüklenirken hata - lütfen tekrar deneyin.";

$_t["tr"]["Error exec'ing the mv command."] = "mv komutu işlenirken hata oluştu.";

$_t["tr"]["You must create an account before you can upload packages."] = "Paket yükleyebilmek için bir hesap oluşturmalısınız.";

$_t["tr"]["Package upload successful."] = "Paket başarıyla yüklendi.";

$_t["tr"]["Overwrite existing package?"] = "Mevcut paketin üzerine yazılsın mı?";

$_t["tr"]["You did not specify a package name."] = "Bir paket adı belirlemediniz.";

$_t["tr"]["Error trying to unpack upload - PKGBUILD does not exist."] = "Yüklenen dosya açılırken hata - PKGBUILD mevcut değil.";

$_t["tr"]["Could not create incoming directory: %s."] = "Gelen dizin oluşturulamadı: %s.";

$_t["tr"]["Upload package file"] = "Paket yükle";

$_t["tr"]["Package Location"] = "Paket Konumu";

$_t["tr"]["Missing url variable in PKGBUILD."] = "PKGBUILD içinde url değişkeni bulunamadı.";

$_t["tr"]["Package names do not match."] = "Paket isimleri uyuşmuyor.";

$_t["tr"]["Package Category"] = "Paket Kategorisi";

$_t["tr"]["Could not change to directory %s."] = "%s dizinine geçilemedi.";

$_t["tr"]["You did not tag the 'overwrite' checkbox."] = "'üzerine yaz' kutusunu işaretlemediniz.";

$_t["tr"]["Invalid name: only lowercase letters are allowed."] = "Geçersiz isim: yalnızca küçük harf kullanılabilir.";

$_t["tr"]["Missing pkgver variable in PKGBUILD."] = "PKGBUILD içinde pkgver değişkeni bulunamadı.";

$_t["tr"]["Package name"] = "Paket adı";

$_t["tr"]["Upload"] = "Yükle";

$_t["tr"]["Missing md5sums variable in PKGBUILD."] = "PKGBUILD içinde md5sums değişkeni bulunamadı.";

$_t["tr"]["Missing pkgrel variable in PKGBUILD."] = "PKGBUILD içinde pkgrel değişkeni bulunamadı.";

$_t["tr"]["Missing pkgname variable in PKGBUILD."] = "PKGBUILD içinde pkgname değişkeni bulunamadı.";

$_t["tr"]["Error - No file uploaded"] = "Hata - Yüklenecek dosya yok";

$_t["tr"]["You are not allowed to overwrite the %h%s%h package."] = "%h%s%h paketi üzerinde değişiklik yapma yetkiniz yok.";

$_t["tr"]["Select Location"] = "Konum Seçin";

$_t["tr"]["Select Category"] = "Kategori Seçin";

$_t["tr"]["Comment"] = "Yorum";

$_t["tr"]["Could not create directory %s."] = "%s dizini oluşturulamadı.";

$_t["tr"]["Unknown file format for uploaded file."] = "Yüklenen dosya biçimi bilinmiyor.";

$_t["tr"]["Missing source variable in PKGBUILD."] = "PKGBUILD içinde source değişkeni bulunamadı.";

$_t["tr"]["Sorry, uploads are not permitted by this server."] = "Üzgünüm, bu sunucu üzerinden yükleme kabul edilmiyor.";

$_t["tr"]["You must supply a comment for this upload/change."] = "Bu yükleme/değişiklik için bir yorum belirtmelisiniz.";

$_t["tr"]["Yes"] = "Evet";

$_t["tr"]["Package URL is missing a protocol (ie. http:// ,ftp://)"] = "Paket URL protokolü hatalı (ör. http:// ,ftp://)";

$_t["tr"]["Could not re-tar"] = "Yeniden tarlanamadı";

$_t["tr"]["Binary packages and filelists are not allowed for upload."] = "İkili paket ve dosya listesi yüklemelerine izin verilmiyor.";

$_t["tr"]["Missing arch variable in PKGBUILD."] = "PKGBUILD içinde arch değişkeni bulunamadı.";

$_t["tr"]["Missing license variable in PKGBUILD."] = "PKGBUILD içinde license değişkeni bulunamadı.";

