#!/bin/bash

aurroot=/srv/http/sites/aur

echo "--------------------"
date

# Update the CVS tree.
# Show a bit of the beginning output.
cd $aurroot/cvs
echo "Updating CVS..."
cvs update -d 2>&1 | grep "^P\|^U\|repository"
cd -

# tupkgupdate <repodir> <cvsdir> <incomingdir>
$aurroot/aur/tupkg/update/tupkgupdate --delete --paranoid /srv/ftp/community/os/i686 $aurroot/cvs $aurroot/packages/full

