#!/bin/bash

aurroot=/srv/http/aur

# Set HOME for correct cvs auth.
HOME=$aurroot

echo "--------------------"
date

# Update the CVS tree.
# Filter out useless output.
cd $aurroot/cvs
echo "Updating CVS..."
cvs update -dP 2>&1 | grep -v "Updating"

# tupkgupdate <repodir> <cvsdir> <incomingdir>
$aurroot/aur/tupkg/update/tupkgupdate -c $aurroot/tupkgs.conf --delete --paranoid /srv/ftp/community/os/i686 $aurroot/cvs $aurroot/packages/full

