#!/usr/bin/python -O
#
# Description:
# ------------
# This is the client-side portion of the Trusted User package
# manager.  The TUs will use this program to upload packages into
# the AUR.  For more information, see the ../README.txt file.
#
# Python Indentation:
# -------------------
# Use tabs not spaces.  If you use vim, the following comment will
# configure it to use tabs.
# vim: ts=2 sw=2 noet ft=python
#



# TODO write the code
#
