"""add indicies on PackageBases for RSS order by

Revision ID: 38e5b9982eea
Revises: 7d65d35fae45
Create Date: 2024-08-03 01:35:39.104283

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38e5b9982eea'
down_revision = '7d65d35fae45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('BasesModifiedTS', 'PackageBases', ['ModifiedTS'], unique=False)
    op.create_index('BasesSubmittedTS', 'PackageBases', ['SubmittedTS'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('BasesSubmittedTS', table_name='PackageBases')
    op.drop_index('BasesModifiedTS', table_name='PackageBases')
    # ### end Alembic commands ###
