<?
# INSTRUCTIONS TO TRANSLATORS
#
# This file contains the i18n translations for a subset of the
# Arch Linux User-community Repository (AUR).  This is a PHP
# script, and as such, you MUST pay great attention to the syntax.
# If your text contains any double-quotes ("), you MUST escape
# them with the backslash character (\).
#

include_once("translator.inc");
global $_t;

$_t["en"]["Under construction..."] = "Under construction...";
# $_t["es"]["Under construction..."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Under construction..."] = "--> Traduction française ici. <--";
$_t["de"]["Under construction..."] = "Noch nicht fertig gestellt ...";
$_t["pl"]["Under construction..."] = "Prace trwają...";

$_t["en"]["Account Suspended:"] = "Account Suspended:";
# $_t["es"]["Account Suspended:"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Account Suspended:"] = "--> Traduction française ici. <--";
$_t["de"]["Account Suspended:"] = "Benutzer-Konto gesperrt:";
$_t["pl"]["Account Suspended:"] = "Konto zablokowane:";

$_t["en"]["Notify:"] = "Notify:";
# $_t["es"]["Notify:"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Notify:"] = "--> Traduction française ici. <--";
$_t["de"]["Notify:"] = "Info:";
$_t["pl"]["Notify:"] = "Powiadomienie:";

$_t["en"]["Trusted User"] = "Trusted User";
# $_t["es"]["Trusted User"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Trusted User"] = "--> Traduction française ici. <--";
$_t["de"]["Trusted User"] = "Vertrauenswürdiger Benutzer";
$_t["pl"]["Trusted User"] = "Zaufany użytkownik";

$_t["en"]["Normal User"] = "Normal User";
# $_t["es"]["Normal User"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Normal User"] = "--> Traduction française ici. <--";
$_t["de"]["Normal User"] = "Normaler Benutzer";
$_t["pl"]["Normal User"] = "Zwykły użytkownik";

$_t["en"]["Password:"] = "Password:";
# $_t["es"]["Password:"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Password:"] = "--> Traduction française ici. <--";
$_t["de"]["Password:"] = "Passwort";
$_t["pl"]["Password:"] = "Hasło:";

$_t["en"]["Email Address:"] = "Email Address:";
# $_t["es"]["Email Address:"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Email Address:"] = "--> Traduction française ici. <--";
$_t["de"]["Email Address:"] = "Email-Addresse:";
$_t["pl"]["Email Address:"] = "Adres e-mail:";

$_t["en"]["Confirm:"] = "Confirm:";
# $_t["es"]["Confirm:"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Confirm:"] = "--> Traduction française ici. <--";
$_t["de"]["Confirm:"] = "Bestätigen:";
$_t["pl"]["Confirm:"] = "Potwierdź:";

$_t["en"]["Real Name:"] = "Real Name:";
# $_t["es"]["Real Name:"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Real Name:"] = "--> Traduction française ici. <--";
$_t["de"]["Real Name:"] = "Tatsächlicher Name";
$_t["pl"]["Real Name:"] = "Imię i nazwisko:";

$_t["en"]["Account Type:"] = "Account Type:";
# $_t["es"]["Account Type:"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Account Type:"] = "--> Traduction française ici. <--";
$_t["de"]["Account Type:"] = "Art des Benutzerkontos:";
$_t["pl"]["Account Type:"] = "Rodzaj konta:";

$_t["en"]["IRC Nick:"] = "IRC Nick:";
# $_t["es"]["IRC Nick:"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["IRC Nick:"] = "--> Traduction française ici. <--";
$_t["de"]["IRC Nick:"] = "IRC Kürzel";
$_t["pl"]["IRC Nick:"] = "Nick na IRC-u:";

$_t["en"]["Language:"] = "Language:";
# $_t["es"]["Language:"] = "--> Traducción espańola aquí. <--";
$_t["fr"]["Language:"] = "Langue:";
$_t["de"]["Language:"] = "Sprache:";
$_t["pl"]["Language:"] = "Język:";

$_t["en"]["Developer"] = "Developer";
# $_t["es"]["Developer"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Developer"] = "--> Traduction française ici. <--";
$_t["de"]["Developer"] = "Entwickler:";
$_t["pl"]["Developer"] = "Developer";

$_t["en"]["New Package Notify:"] = "New Package Notify:";
# $_t["es"]["New Package Notify:"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["New Package Notify:"] = "--> Traduction française ici. <--";
$_t["de"]["New Package Notify:"] = "Benachrichtigung über neue Packete:";
$_t["pl"]["New Package Notify:"] = "Powiadamiaj o nowych pakietach:";

$_t["en"]["Password fields do not match."] = "Password fields do not match.";
# $_t["es"]["Password fields do not match."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Password fields do not match."] = "--> Traduction française ici. <--";
$_t["de"]["Password fields do not match."] = "Passwort stimmt nicht überein!";
$_t["pl"]["Password fields do not match."] = "Hasła nie zgadzają się.";

$_t["en"]["Error trying to create account, %h%s%h: %s."] = "Error trying to create account, %h%s%h: %s.";
# $_t["es"]["Error trying to create account, %h%s%h: %s."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Error trying to create account, %h%s%h: %s."] = "--> Traduction française ici. <--";
$_t["de"]["Error trying to create account, %h%s%h: %s."] = "Fehler beim Erstellen des Benutzerkontos, %h%s%h: %s.";
$_t["pl"]["Error trying to create account, %h%s%h: %s."] = "Błąd podczas tworzenia konta %h%s%h: %s.";

$_t["en"]["Missing a required field."] = "Missing a required field.";
# $_t["es"]["Missing a required field."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Missing a required field."] = "--> Traduction française ici. <--";
$_t["de"]["Missing a required field."] = "Erforderliches Feld nicht ausgefüllt.";
$_t["pl"]["Missing a required field."] = "Brakuje wymaganego pola.";

$_t["en"]["This address is already in use."] = "This address is already in use.";
# $_t["es"]["This address is already in use."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["This address is already in use."] = "--> Traduction française ici. <--";
$_t["de"]["This address is already in use."] = "Diese Addresse ist schon in Betrieb.";
$_t["pl"]["This address is already in use."] = "Ten adres jest już używany.";

$_t["en"]["Language is not currently supported."] = "Language is not currently supported.";
# $_t["es"]["Language is not currently supported."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Language is not currently supported."] = "--> Traduction française ici. <--";
$_t["de"]["Language is not currently supported."] = "Sprache im moment noch nicht unterstützt.";
$_t["pl"]["Language is not currently supported."] = "Język nie jest obecnie obsługiwany.";

$_t["en"]["The email address is invalid."] = "The email address is invalid.";
# $_t["es"]["The email address is invalid."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["The email address is invalid."] = "--> Traduction française ici. <--";
$_t["de"]["The email address is invalid."] = "Ungültige Email.";
$_t["pl"]["The email address is invalid."] = "Adres e-mail jest nieprawidłowy.";

$_t["en"]["Re-type password:"] = "Re-type password:";
# $_t["es"]["Re-type password:"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Re-type password:"] = "--> Traduction française ici. <--";
$_t["de"]["Re-type password:"] = "Wiederhole Passwort:";
$_t["pl"]["Re-type password:"] = "Hasło (ponownie):";

$_t["en"]["The account, %h%s%h, has been successfully created."] = "The account, %h%s%h, has been successfully created.";
# $_t["es"]["The account, %h%s%h, has been successfully created."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["The account, %h%s%h, has been successfully created."] = "--> Traduction française ici. <--";
$_t["de"]["The account, %h%s%h, has been successfully created."] = "Benutzerkonto, %h%s%h, wurde erfolgreich erstellt.";
$_t["pl"]["The account, %h%s%h, has been successfully created."] = "Konto %h%s%h zostało pomyślnie utworzone.";

$_t["en"]["Click on the Home link above to login."] = "Click on the Home link above to login.";
# $_t["es"]["Click on the Home link above to login."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Click on the Home link above to login."] = "--> Traduction française ici. <--";
$_t["de"]["Click on the Home link above to login."] = "Klicke auf den 'Home'-Link um dich anzumelden.";
$_t["pl"]["Click on the Home link above to login."] = "Kliknij na linku Start powyżej aby się zalogować.";

$_t["en"]["The address, %h%s%h, is already in use."] = "The address, %h%s%h, is already in use.";
# $_t["es"]["The address, %h%s%h, is already in use."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["The address, %h%s%h, is already in use."] = "--> Traduction française ici. <--";
$_t["de"]["The address, %h%s%h, is already in use."] = "Die Addresse, %h%s%h, ist schon in Betrieb.";
$_t["pl"]["The address, %h%s%h, is already in use."] = "Adres %h%s%h jest już używany.";

// next field already specified on lines 29-32
$_t["en"]["Trusted user"] = "Trusted user";
# $_t["es"]["Trusted user"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Trusted user"] = "--> Traduction française ici. <--";
# $_t["de"]["Trusted user"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Trusted user"] = "Zaufany użytkownik";

// next field already specified on lines 34-37
$_t["en"]["Normal user"] = "Normal user";
# $_t["es"]["Normal user"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Normal user"] = "--> Traduction française ici. <--";
# $_t["de"]["Normal user"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Normal user"] = "Zwykły użytkownik";

$_t["en"]["Any type"] = "Any type";
# $_t["es"]["Any type"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Any type"] = "--> Traduction française ici. <--";
$_t["de"]["Any type"] = "Beliebiger Typ";
$_t["pl"]["Any type"] = "Dowolny rodzaj";

$_t["en"]["No results matched your search criteria."] = "No results matched your search criteria.";
# $_t["es"]["No results matched your search criteria."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["No results matched your search criteria."] = "--> Traduction française ici. <--";
$_t["de"]["No results matched your search criteria."] = "Suche ergab keine Treffer";
$_t["pl"]["No results matched your search criteria."] = "Wyszukiwanie nie przyniosło rezultatu.";

$_t["en"]["Never"] = "Never";
# $_t["es"]["Never"] = "--> Traducción espańola aquí. <--";
$_t["fr"]["Never"] = "Jamais";
$_t["de"]["Never"] = "Nie";
$_t["pl"]["Never"] = "Nigdy";

$_t["en"]["Active"] = "Active";
# $_t["es"]["Active"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Active"] = "--> Traduction française ici. <--";
$_t["de"]["Active"] = "Aktiv";
$_t["pl"]["Active"] = "Aktywne";

$_t["en"]["Suspended"] = "Suspended";
# $_t["es"]["Suspended"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Suspended"] = "--> Traduction française ici. <--";
$_t["de"]["Suspended"] = "Gesperrt";
$_t["pl"]["Suspended"] = "Zablokowane";

$_t["en"]["The username, %h%s%h, is already in use."] = "The username, %h%s%h, is already in use.";
# $_t["es"]["The username, %h%s%h, is already in use."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["The username, %h%s%h, is already in use."] = "--> Traduction française ici. <--";
$_t["de"]["The username, %h%s%h, is already in use."] = "Dieser Benutzername, %h%s%h, ist schon besetzt.";
$_t["pl"]["The username, %h%s%h, is already in use."] = "Nazwa użytkownika %h%s%h jest już używana.";

$_t["en"]["Type"] = "Type";
# $_t["es"]["Type"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Type"] = "--> Traduction française ici. <--";
$_t["de"]["Type"] = "Typ";
$_t["pl"]["Type"] = "Rodzaj";

$_t["en"]["Status"] = "Status";
# $_t["es"]["Status"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Status"] = "--> Traduction française ici. <--";
$_t["de"]["Status"] = "Status";
$_t["pl"]["Status"] = "Status";

// next field already specified on lines 64-67
$_t["en"]["IRC Nick"] = "IRC Nick";
# $_t["es"]["IRC Nick"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["IRC Nick"] = "--> Traduction française ici. <--";
# $_t["de"]["IRC Nick"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["IRC Nick"] = "Nick na IRC-u";

$_t["en"]["Last Voted"] = "Last Voted";
# $_t["es"]["Last Voted"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Last Voted"] = "--> Traduction française ici. <--";
$_t["de"]["Last Voted"] = "Letzte Abstimmung";
$_t["pl"]["Last Voted"] = "Ostatni głos";

// next field already specified on lines 54-57
$_t["en"]["Real Name"] = "Real Name";
# $_t["es"]["Real Name"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Real Name"] = "--> Traduction française ici. <--";
# $_t["de"]["Real Name"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Real Name"] = "Imię i nazwisko";

$_t["en"]["Username:"] = "Username:";
# $_t["es"]["Username:"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Username:"] = "--> Traduction française ici. <--";
$_t["de"]["Username:"] = "Benutzername";
$_t["pl"]["Username:"] = "Nazwa użytkownika:";

$_t["en"]["Sort by"] = "Sort by";
# $_t["es"]["Sort by"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Sort by"] = "--> Traduction française ici. <--";
$_t["de"]["Sort by"] = "Sortier-Kriterium";
$_t["pl"]["Sort by"] = "Sortuj według";

$_t["en"]["Account Type"] = "Account Type";
# $_t["es"]["Account Type"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Account Type"] = "--> Traduction française ici. <--";
$_t["de"]["Account Type"] = "Art des Benutzerkontos";
$_t["pl"]["Account Type"] = "Rodzaj konta";

$_t["en"]["Account Suspended"] = "Account Suspended";
# $_t["es"]["Account Suspended"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Account Suspended"] = "--> Traduction française ici. <--";
$_t["de"]["Account Suspended"] = "Benutzerkonto gesperrt";
$_t["pl"]["Account Suspended"] = "Konto zablokowane";

$_t["en"]["Email address"] = "Email address";
# $_t["es"]["Email address"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Email address"] = "--> Traduction française ici. <--";
$_t["de"]["Email address"] = "Email-Addresse";
$_t["pl"]["Email address"] = "Adres e-mail";

$_t["en"]["Last vote"] = "Last vote";
# $_t["es"]["Last vote"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Last vote"] = "--> Traduction française ici. <--";
$_t["de"]["Last vote"] = "Letzte Abstimmung";
$_t["pl"]["Last vote"] = "Ostatni głos";

$_t["en"]["Regular users can edit their own account."] = "Regular users can edit their own account.";
# $_t["es"]["Regular users can edit their own account."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Regular users can edit their own account."] = "--> Traduction française ici. <--";
$_t["de"]["Regular users can edit their own account."] = "Reguläre Benutzer können Ihr Benutzerkonto selber bearbeiten.";
$_t["pl"]["Regular users can edit their own account."] = "Zwykli użytkownicy mogą edytować swoje konto.";

$_t["en"]["Edit Account"] = "Edit Account";
# $_t["es"]["Edit Account"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Edit Account"] = "--> Traduction française ici. <--";
$_t["de"]["Edit Account"] = "Benutzerkonto bearbeiten";
$_t["pl"]["Edit Account"] = "Edytuj konto";

$_t["en"]["Use this form to search existing accounts."] = "Use this form to search existing accounts.";
# $_t["es"]["Use this form to search existing accounts."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Use this form to search existing accounts."] = "--> Traduction française ici. <--";
$_t["de"]["Use this form to search existing accounts."] = "Hier kann nach bestehenden Benutzerkontos gesucht werden.";
$_t["pl"]["Use this form to search existing accounts."] = "Przy użyciu tego formularza możesz przeszukać istniejące konta.";

$_t["en"]["You are not allowed to access this area."] = "You are not allowed to access this area.";
# $_t["es"]["You are not allowed to access this area."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["You are not allowed to access this area."] = "--> Traduction française ici. <--";
$_t["de"]["You are not allowed to access this area."] = "Zugriff auf diese Seite verweigert.";
$_t["pl"]["You are not allowed to access this area."] = "Nie masz uprawnień do oglądania tej strony.";

$_t["en"]["Use this form to create an account."] = "Use this form to create an account.";
# $_t["es"]["Use this form to create an account."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Use this form to create an account."] = "--> Traduction française ici. <--";
$_t["de"]["Use this form to create an account."] = "Hier kann das Benutzerkonto erstellt werden.";
$_t["pl"]["Use this form to create an account."] = "Przy użyciu tego formularza możesz utworzyć konto.";

$_t["en"]["Use this form to update your account."] = "Use this form to update your account.";
# $_t["es"]["Use this form to update your account."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Use this form to update your account."] = "--> Traduction française ici. <--";
$_t["de"]["Use this form to update your account."] = "Hier kann das Benutzerkonto bearbeitet werden.";
$_t["pl"]["Use this form to update your account."] = "Przy użyciu tego formularza możesz uaktualnić swoje konto.";

$_t["en"]["Leave the password fields blank to keep your same password."] = "Leave the password fields blank to keep your same password.";
# $_t["es"]["Leave the password fields blank to keep your same password."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Leave the password fields blank to keep your same password."] = "--> Traduction française ici. <--";
# $_t["de"]["Leave the password fields blank to keep your same password."] = "Passwort-Felder frei lassen, um schon bestehendes Passwort zu benutzen.";
$_t["pl"]["Leave the password fields blank to keep your same password."] = "Pozostaw pola z hasłem puste aby nie zmieniać swojego hasła.";

$_t["en"]["Could not retrieve information for the specified user."] = "Could not retrieve information for the specified user.";
# $_t["es"]["Could not retrieve information for the specified user."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Could not retrieve information for the specified user."] = "--> Traduction française ici. <--";
# $_t["de"]["Could not retrieve information for the specified user."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Could not retrieve information for the specified user."] = "Uzyskanie informacji o podanym użytkowniku nie powiodło się.";

$_t["en"]["You do not have permission to edit this account."] = "You do not have permission to edit this account.";
# $_t["es"]["You do not have permission to edit this account."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["You do not have permission to edit this account."] = "--> Traduction française ici. <--";
$_t["de"]["You do not have permission to edit this account."] = "Zugriff für das Bearbeiten dieses Benutzerkontos verweigert.";
$_t["pl"]["You do not have permission to edit this account."] = "Nie masz uprawnień do edycji tego konta.";

?>