<?
# INSTRUCTIONS TO TRANSLATORS
#
# This file contains the i18n translations for a subset of the
# Arch Linux User-community Repository (AUR).  This is a PHP
# script, and as such, you MUST pay great attention to the syntax.
# If your text contains any double-quotes ("), you MUST escape
# them with the backslash character (\).
#

include_once("translator.inc");
global $_t;

$_t["en"]["Under construction..."] = "Under construction...";
# $_t["es"]["Under construction..."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Under construction..."] = "--> Traduction française ici. <--";
# $_t["de"]["Under construction..."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Account Suspended:"] = "Account Suspended:";
# $_t["es"]["Account Suspended:"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Account Suspended:"] = "--> Traduction française ici. <--";
# $_t["de"]["Account Suspended:"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Notify:"] = "Notify:";
# $_t["es"]["Notify:"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Notify:"] = "--> Traduction française ici. <--";
# $_t["de"]["Notify:"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Trusted User"] = "Trusted User";
# $_t["es"]["Trusted User"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Trusted User"] = "--> Traduction française ici. <--";
# $_t["de"]["Trusted User"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Normal User"] = "Normal User";
# $_t["es"]["Normal User"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Normal User"] = "--> Traduction française ici. <--";
# $_t["de"]["Normal User"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Password:"] = "Password:";
# $_t["es"]["Password:"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Password:"] = "--> Traduction française ici. <--";
# $_t["de"]["Password:"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Email Address:"] = "Email Address:";
# $_t["es"]["Email Address:"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Email Address:"] = "--> Traduction française ici. <--";
# $_t["de"]["Email Address:"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Confirm:"] = "Confirm:";
# $_t["es"]["Confirm:"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Confirm:"] = "--> Traduction française ici. <--";
# $_t["de"]["Confirm:"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Real Name:"] = "Real Name:";
# $_t["es"]["Real Name:"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Real Name:"] = "--> Traduction française ici. <--";
# $_t["de"]["Real Name:"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Account Type:"] = "Account Type:";
# $_t["es"]["Account Type:"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Account Type:"] = "--> Traduction française ici. <--";
# $_t["de"]["Account Type:"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["IRC Nick:"] = "IRC Nick:";
# $_t["es"]["IRC Nick:"] = "--> Traducción española aquí. <--";
# $_t["fr"]["IRC Nick:"] = "--> Traduction française ici. <--";
# $_t["de"]["IRC Nick:"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Language:"] = "Language:";
# $_t["es"]["Language:"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Language:"] = "--> Traduction française ici. <--";
# $_t["de"]["Language:"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Developer"] = "Developer";
# $_t["es"]["Developer"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Developer"] = "--> Traduction française ici. <--";
# $_t["de"]["Developer"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["New Package Notify:"] = "New Package Notify:";
# $_t["es"]["New Package Notify:"] = "--> Traducción española aquí. <--";
# $_t["fr"]["New Package Notify:"] = "--> Traduction française ici. <--";
# $_t["de"]["New Package Notify:"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Password fields do not match."] = "Password fields do not match.";
# $_t["es"]["Password fields do not match."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Password fields do not match."] = "--> Traduction française ici. <--";
# $_t["de"]["Password fields do not match."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Error trying to create account, %h%s%h: %s."] = "Error trying to create account, %h%s%h: %s.";
# $_t["es"]["Error trying to create account, %h%s%h: %s."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Error trying to create account, %h%s%h: %s."] = "--> Traduction française ici. <--";
# $_t["de"]["Error trying to create account, %h%s%h: %s."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Missing a required field."] = "Missing a required field.";
# $_t["es"]["Missing a required field."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Missing a required field."] = "--> Traduction française ici. <--";
# $_t["de"]["Missing a required field."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["This address is already in use."] = "This address is already in use.";
# $_t["es"]["This address is already in use."] = "--> Traducción española aquí. <--";
# $_t["fr"]["This address is already in use."] = "--> Traduction française ici. <--";
# $_t["de"]["This address is already in use."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Language is not currently supported."] = "Language is not currently supported.";
# $_t["es"]["Language is not currently supported."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Language is not currently supported."] = "--> Traduction française ici. <--";
# $_t["de"]["Language is not currently supported."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["The email address is invalid."] = "The email address is invalid.";
# $_t["es"]["The email address is invalid."] = "--> Traducción española aquí. <--";
# $_t["fr"]["The email address is invalid."] = "--> Traduction française ici. <--";
# $_t["de"]["The email address is invalid."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Re-type password:"] = "Re-type password:";
# $_t["es"]["Re-type password:"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Re-type password:"] = "--> Traduction française ici. <--";
# $_t["de"]["Re-type password:"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["The account, %h%s%h, has been successfully created."] = "The account, %h%s%h, has been successfully created.";
# $_t["es"]["The account, %h%s%h, has been successfully created."] = "--> Traducción española aquí. <--";
# $_t["fr"]["The account, %h%s%h, has been successfully created."] = "--> Traduction française ici. <--";
# $_t["de"]["The account, %h%s%h, has been successfully created."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Click on the Home link above to login."] = "Click on the Home link above to login.";
# $_t["es"]["Click on the Home link above to login."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Click on the Home link above to login."] = "--> Traduction française ici. <--";
# $_t["de"]["Click on the Home link above to login."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["The address, %h%s%h, is already in use."] = "The address, %h%s%h, is already in use.";
# $_t["es"]["The address, %h%s%h, is already in use."] = "--> Traducción española aquí. <--";
# $_t["fr"]["The address, %h%s%h, is already in use."] = "--> Traduction française ici. <--";
# $_t["de"]["The address, %h%s%h, is already in use."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Trusted user"] = "Trusted user";
# $_t["es"]["Trusted user"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Trusted user"] = "--> Traduction française ici. <--";
# $_t["de"]["Trusted user"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Normal user"] = "Normal user";
# $_t["es"]["Normal user"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Normal user"] = "--> Traduction française ici. <--";
# $_t["de"]["Normal user"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Any type"] = "Any type";
# $_t["es"]["Any type"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Any type"] = "--> Traduction française ici. <--";
# $_t["de"]["Any type"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["No results matched your search criteria."] = "No results matched your search criteria.";
# $_t["es"]["No results matched your search criteria."] = "--> Traducción española aquí. <--";
# $_t["fr"]["No results matched your search criteria."] = "--> Traduction française ici. <--";
# $_t["de"]["No results matched your search criteria."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Never"] = "Never";
# $_t["es"]["Never"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Never"] = "--> Traduction française ici. <--";
# $_t["de"]["Never"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Active"] = "Active";
# $_t["es"]["Active"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Active"] = "--> Traduction française ici. <--";
# $_t["de"]["Active"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Suspended"] = "Suspended";
# $_t["es"]["Suspended"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Suspended"] = "--> Traduction française ici. <--";
# $_t["de"]["Suspended"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["The username, %h%s%h, is already in use."] = "The username, %h%s%h, is already in use.";
# $_t["es"]["The username, %h%s%h, is already in use."] = "--> Traducción española aquí. <--";
# $_t["fr"]["The username, %h%s%h, is already in use."] = "--> Traduction française ici. <--";
# $_t["de"]["The username, %h%s%h, is already in use."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Type"] = "Type";
# $_t["es"]["Type"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Type"] = "--> Traduction française ici. <--";
# $_t["de"]["Type"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Status"] = "Status";
# $_t["es"]["Status"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Status"] = "--> Traduction française ici. <--";
# $_t["de"]["Status"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["IRC Nick"] = "IRC Nick";
# $_t["es"]["IRC Nick"] = "--> Traducción española aquí. <--";
# $_t["fr"]["IRC Nick"] = "--> Traduction française ici. <--";
# $_t["de"]["IRC Nick"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Last Voted"] = "Last Voted";
# $_t["es"]["Last Voted"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Last Voted"] = "--> Traduction française ici. <--";
# $_t["de"]["Last Voted"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Real Name"] = "Real Name";
# $_t["es"]["Real Name"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Real Name"] = "--> Traduction française ici. <--";
# $_t["de"]["Real Name"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Username:"] = "Username:";
# $_t["es"]["Username:"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Username:"] = "--> Traduction française ici. <--";
# $_t["de"]["Username:"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Sort by"] = "Sort by";
# $_t["es"]["Sort by"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Sort by"] = "--> Traduction française ici. <--";
# $_t["de"]["Sort by"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Account Type"] = "Account Type";
# $_t["es"]["Account Type"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Account Type"] = "--> Traduction française ici. <--";
# $_t["de"]["Account Type"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Account Suspended"] = "Account Suspended";
# $_t["es"]["Account Suspended"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Account Suspended"] = "--> Traduction française ici. <--";
# $_t["de"]["Account Suspended"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Email address"] = "Email address";
# $_t["es"]["Email address"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Email address"] = "--> Traduction française ici. <--";
# $_t["de"]["Email address"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Last vote"] = "Last vote";
# $_t["es"]["Last vote"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Last vote"] = "--> Traduction française ici. <--";
# $_t["de"]["Last vote"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Regular users can edit their own account."] = "Regular users can edit their own account.";
# $_t["es"]["Regular users can edit their own account."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Regular users can edit their own account."] = "--> Traduction française ici. <--";
# $_t["de"]["Regular users can edit their own account."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Edit Account"] = "Edit Account";
# $_t["es"]["Edit Account"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Edit Account"] = "--> Traduction française ici. <--";
# $_t["de"]["Edit Account"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Use this form to search existing accounts."] = "Use this form to search existing accounts.";
# $_t["es"]["Use this form to search existing accounts."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Use this form to search existing accounts."] = "--> Traduction française ici. <--";
# $_t["de"]["Use this form to search existing accounts."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["You are not allowed to access this area."] = "You are not allowed to access this area.";
# $_t["es"]["You are not allowed to access this area."] = "--> Traducción española aquí. <--";
# $_t["fr"]["You are not allowed to access this area."] = "--> Traduction française ici. <--";
# $_t["de"]["You are not allowed to access this area."] = "--> Deutsche Übersetzung hier. <--";

?>