<?
# INSTRUCTIONS TO TRANSLATORS
#
# This file contains the i18n translations for a subset of the
# Arch Linux User-community Repository (AUR).  This is a PHP
# script, and as such, you MUST pay great attention to the syntax.
# If your text contains any double-quotes ("), you MUST escape
# them with the backslash character (\).
#

include_once("translator.inc");
global $_t;

$_t["en"]["Missing a required field."] = "Missing a required field.";
# $_t["es"]["Missing a required field."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Missing a required field."] = "--> Traduction française ici. <--";
# $_t["de"]["Missing a required field."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Missing a required field."] = "Brakuje wymaganego pola.";

$_t["en"]["The account, %h%s%h, has been successfully created."] = "The account, %h%s%h, has been successfully created.";
# $_t["es"]["The account, %h%s%h, has been successfully created."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["The account, %h%s%h, has been successfully created."] = "--> Traduction française ici. <--";
# $_t["de"]["The account, %h%s%h, has been successfully created."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["The account, %h%s%h, has been successfully created."] = "Konto %h%s%h zostało pomyślnie utworzone.";

$_t["en"]["Error trying to modify account, %h%s%h: %s."] = "Error trying to modify account, %h%s%h: %s.";
# $_t["es"]["Error trying to modify account, %h%s%h: %s."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Error trying to modify account, %h%s%h: %s."] = "--> Traduction française ici. <--";
# $_t["de"]["Error trying to modify account, %h%s%h: %s."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Error trying to modify account, %h%s%h: %s."] = "Błąd podczas modyfikacji konta %h%s%h: %s.";

$_t["en"]["The email address is invalid."] = "The email address is invalid.";
# $_t["es"]["The email address is invalid."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["The email address is invalid."] = "--> Traduction française ici. <--";
# $_t["de"]["The email address is invalid."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["The email address is invalid."] = "Adres e-mail jest nieprawidłowy.";

$_t["en"]["Error trying to create account, %h%s%h: %s."] = "Error trying to create account, %h%s%h: %s.";
# $_t["es"]["Error trying to create account, %h%s%h: %s."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Error trying to create account, %h%s%h: %s."] = "--> Traduction française ici. <--";
# $_t["de"]["Error trying to create account, %h%s%h: %s."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Error trying to create account, %h%s%h: %s."] = "Błąd podczas tworzenia konta %h%s%h: %s.";

$_t["en"]["The username, %h%s%h, is already in use."] = "The username, %h%s%h, is already in use.";
# $_t["es"]["The username, %h%s%h, is already in use."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["The username, %h%s%h, is already in use."] = "--> Traduction française ici. <--";
# $_t["de"]["The username, %h%s%h, is already in use."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["The username, %h%s%h, is already in use."] = "Nazwa użytkownika %h%s%h jest już używana.";

$_t["en"]["Account Type"] = "Account Type";
# $_t["es"]["Account Type"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Account Type"] = "--> Traduction française ici. <--";
# $_t["de"]["Account Type"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Account Type"] = "Rodzaj konta";

$_t["en"]["The account, %h%s%h, has been successfully modified."] = "The account, %h%s%h, has been successfully modified.";
# $_t["es"]["The account, %h%s%h, has been successfully modified."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["The account, %h%s%h, has been successfully modified."] = "--> Traduction française ici. <--";
# $_t["de"]["The account, %h%s%h, has been successfully modified."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["The account, %h%s%h, has been successfully modified."] = "Konto %h%s%h zostało pomyślnie utworzone.";

$_t["en"]["Account Suspended"] = "Account Suspended";
# $_t["es"]["Account Suspended"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Account Suspended"] = "--> Traduction française ici. <--";
# $_t["de"]["Account Suspended"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Account Suspended"] = "Konto zablokowane";

$_t["en"]["New Package Notify"] = "New Package Notify";
# $_t["es"]["New Package Notify"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["New Package Notify"] = "--> Traduction française ici. <--";
# $_t["de"]["New Package Notify"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["New Package Notify"] = "Powiadamiaj o nowych pakietach";

$_t["en"]["IRC Nick"] = "IRC Nick";
# $_t["es"]["IRC Nick"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["IRC Nick"] = "--> Traduction française ici. <--";
# $_t["de"]["IRC Nick"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["IRC Nick"] = "Nick na IRC-u";

$_t["en"]["Trusted user"] = "Trusted user";
# $_t["es"]["Trusted user"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Trusted user"] = "--> Traduction française ici. <--";
# $_t["de"]["Trusted user"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Trusted user"] = "Zaufany użytkownik";

$_t["en"]["Normal user"] = "Normal user";
# $_t["es"]["Normal user"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Normal user"] = "--> Traduction française ici. <--";
# $_t["de"]["Normal user"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Normal user"] = "Zwykły użytkownik";

$_t["en"]["Real Name"] = "Real Name";
# $_t["es"]["Real Name"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Real Name"] = "--> Traduction française ici. <--";
# $_t["de"]["Real Name"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Real Name"] = "Imię i nazwisko";

$_t["en"]["Password fields do not match."] = "Password fields do not match.";
# $_t["es"]["Password fields do not match."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Password fields do not match."] = "--> Traduction française ici. <--";
# $_t["de"]["Password fields do not match."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Password fields do not match."] = "Hasła nie zgadzają się.";

$_t["en"]["Language"] = "Language";
# $_t["es"]["Language"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Language"] = "--> Traduction française ici. <--";
# $_t["de"]["Language"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Language"] = "Język";

$_t["en"]["The address, %h%s%h, is already in use."] = "The address, %h%s%h, is already in use.";
# $_t["es"]["The address, %h%s%h, is already in use."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["The address, %h%s%h, is already in use."] = "--> Traduction française ici. <--";
# $_t["de"]["The address, %h%s%h, is already in use."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["The address, %h%s%h, is already in use."] = "Adres %h%s%h jest już używany.";

$_t["en"]["Click on the Home link above to login."] = "Click on the Home link above to login.";
# $_t["es"]["Click on the Home link above to login."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Click on the Home link above to login."] = "--> Traduction française ici. <--";
# $_t["de"]["Click on the Home link above to login."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Click on the Home link above to login."] = "Kliknij na linku Start powyżej aby się zalogować.";

$_t["en"]["Re-type password"] = "Re-type password";
# $_t["es"]["Re-type password"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Re-type password"] = "--> Traduction française ici. <--";
# $_t["de"]["Re-type password"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Re-type password"] = "Hasło (ponownie)";

$_t["en"]["Language is not currently supported."] = "Language is not currently supported.";
# $_t["es"]["Language is not currently supported."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Language is not currently supported."] = "--> Traduction française ici. <--";
# $_t["de"]["Language is not currently supported."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Language is not currently supported."] = "Język nie jest obecnie obsługiwany.";

$_t["en"]["Missing User ID"] = "Missing User ID";
# $_t["es"]["Missing User ID"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Missing User ID"] = "--> Traduction française ici. <--";
# $_t["de"]["Missing User ID"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Missing User ID"] = "Brakuje ID użytkownika";

$_t["en"]["Developer"] = "Developer";
# $_t["es"]["Developer"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Developer"] = "--> Traduction française ici. <--";
# $_t["de"]["Developer"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Developer"] = "Developer";

$_t["en"]["Search'"] = "Search'";
# $_t["es"]["Search'"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Search'"] = "--> Traduction française ici. <--";
# $_t["de"]["Search'"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Search'"] = "Szukaj'";

$_t["en"]["Status"] = "Status";
# $_t["es"]["Status"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Status"] = "--> Traduction française ici. <--";
# $_t["de"]["Status"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Status"] = "Status";

$_t["en"]["No results matched your search criteria."] = "No results matched your search criteria.";
# $_t["es"]["No results matched your search criteria."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["No results matched your search criteria."] = "--> Traduction française ici. <--";
# $_t["de"]["No results matched your search criteria."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["No results matched your search criteria."] = "Wyszukiwanie nie przyniosło rezultatu.";

$_t["en"]["Never"] = "Never";
# $_t["es"]["Never"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Never"] = "--> Traduction française ici. <--";
# $_t["de"]["Never"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Never"] = "Nigdy";

$_t["en"]["Active"] = "Active";
# $_t["es"]["Active"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Active"] = "--> Traduction française ici. <--";
# $_t["de"]["Active"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Active"] = "Aktywne";

$_t["en"]["Last Voted"] = "Last Voted";
# $_t["es"]["Last Voted"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Last Voted"] = "--> Traduction française ici. <--";
# $_t["de"]["Last Voted"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Last Voted"] = "Ostatni głos";

$_t["en"]["Edit Account"] = "Edit Account";
# $_t["es"]["Edit Account"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Edit Account"] = "--> Traduction française ici. <--";
# $_t["de"]["Edit Account"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Edit Account"] = "Edytuj konto";

$_t["en"]["Email address"] = "Email address";
# $_t["es"]["Email address"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Email address"] = "--> Traduction française ici. <--";
# $_t["de"]["Email address"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Email address"] = "Adres e-mail";

$_t["en"]["Type"] = "Type";
# $_t["es"]["Type"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Type"] = "--> Traduction française ici. <--";
# $_t["de"]["Type"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Type"] = "Rodzaj";

$_t["en"]["Sort by"] = "Sort by";
# $_t["es"]["Sort by"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Sort by"] = "--> Traduction française ici. <--";
# $_t["de"]["Sort by"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Sort by"] = "Sortuj według";

$_t["en"]["Any type"] = "Any type";
# $_t["es"]["Any type"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Any type"] = "--> Traduction française ici. <--";
# $_t["de"]["Any type"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Any type"] = "Dowolny rodzaj";

$_t["en"]["Last vote"] = "Last vote";
# $_t["es"]["Last vote"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Last vote"] = "--> Traduction française ici. <--";
# $_t["de"]["Last vote"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Last vote"] = "Ostatni głos";

$_t["en"]["Suspended"] = "Suspended";
# $_t["es"]["Suspended"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Suspended"] = "--> Traduction française ici. <--";
# $_t["de"]["Suspended"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Suspended"] = "Zablokowane";

$_t["en"]["No more results to display."] = "No more results to display.";
# $_t["es"]["No more results to display."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["No more results to display."] = "--> Traduction française ici. <--";
# $_t["de"]["No more results to display."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["No more results to display."] = "Nie ma już rezultatów do wyświetlenia.";

$_t["en"]["A Trusted User cannot assign Developer status."] = "A Trusted User cannot assign Developer status.";
# $_t["es"]["A Trusted User cannot assign Developer status."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["A Trusted User cannot assign Developer status."] = "--> Traduction française ici. <--";
# $_t["de"]["A Trusted User cannot assign Developer status."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["A Trusted User cannot assign Developer status."] = "Zaufany użytkownik nie może nadać statusu developera.";

?>
