<?
# INSTRUCTIONS TO TRANSLATORS
#
# This file contains the i18n translations for a subset of the
# Arch Linux User-community Repository (AUR).  This is a PHP
# script, and as such, you MUST pay great attention to the syntax.
# If your text contains any double-quotes ("), you MUST escape
# them with the backslash character (\).
#

include_once("translator.inc");
global $_t;

$_t["en"]["ArchLinux User-community Repository"] = "ArchLinux User-community Repository";
# $_t["es"]["ArchLinux User-community Repository"] = "--> Traducción española aquí. <--";
# $_t["fr"]["ArchLinux User-community Repository"] = "--> Traduction française ici. <--";
$_t["de"]["ArchLinux User-community Repository"] = "ArchLinux Benutzer-Community Repository";

$_t["en"]["AUR: An ArchLinux project"] = "AUR: An ArchLinux project";
# $_t["es"]["AUR: An ArchLinux project"] = "--> Traducción española aquí. <--";
# $_t["fr"]["AUR: An ArchLinux project"] = "--> Traduction française ici. <--";
$_t["de"]["AUR: An ArchLinux project"] = "AUR: Ein ArchLinux Projekt";

$_t["en"]["Logout"] = "Logout";
# $_t["es"]["Logout"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Logout"] = "--> Traduction française ici. <--";
$_t["de"]["Logout"] = "Abmelden";

$_t["en"]["Manage"] = "Manage";
# $_t["es"]["Manage"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Manage"] = "--> Traduction française ici. <--";
$_t["de"]["Manage"] = "Verwalten";

$_t["en"]["Submit"] = "Submit";
# $_t["es"]["Submit"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Submit"] = "--> Traduction française ici. <--";
$_t["de"]["Submit"] = "Senden";

$_t["en"]["%s: An ArchLinux project"] = "%s: An ArchLinux project";
# $_t["es"]["%s: An ArchLinux project"] = "--> Traducción española aquí. <--";
# $_t["fr"]["%s: An ArchLinux project"] = "--> Traduction française ici. <--";
$_t["de"]["%s: An ArchLinux project"] = "%s: Ein ArchLinux Projekt";

$_t["en"]["Accounts"] = "Accounts";
# $_t["es"]["Accounts"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Accounts"] = "--> Traduction française ici. <--";
$_t["de"]["Accounts"] = "Benutzerkonti";

$_t["en"]["Vote"] = "Vote";
# $_t["es"]["Vote"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Vote"] = "--> Traduction française ici. <--";
$_t["de"]["Vote"] = "Abstimmen";

$_t["en"]["Home"] = "Home";
# $_t["es"]["Home"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Home"] = "--> Traduction française ici. <--";
$_t["de"]["Home"] = "Hauptseite";

$_t["en"]["Packages"] = "Packages";
# $_t["es"]["Packages"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Packages"] = "--> Traduction française ici. <--";
$_t["de"]["Packages"] = "Pakete";

$_t["en"]["Trusted user"] = "Trusted user";
# $_t["es"]["Trusted user"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Trusted user"] = "--> Traduction française ici. <--";
$_t["de"]["Trusted user"] = "Vertrauenswürdiger Benutzer";

$_t["en"]["User"] = "User";
# $_t["es"]["User"] = "--> Traducción española aquí. <--";
# $_t["fr"]["User"] = "--> Traduction française ici. <--";
$_t["de"]["User"] = "Benutzer";

$_t["en"]["Developer"] = "Developer";
# $_t["es"]["Developer"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Developer"] = "--> Traduction française ici. <--";
$_t["de"]["Developer"] = "Entwickler";

?>