<?
# INSTRUCTIONS TO TRANSLATORS
#
# This file contains the i18n translations for a subset of the
# Arch Linux User-community Repository (AUR).  This is a PHP
# script, and as such, you MUST pay great attention to the syntax.
# If your text contains any double-quotes ("), you MUST escape
# them with the backslash character (\).
#

include_once("translator.inc");
global $_t;

$_t["en"]["Password"] = "Password";
# $_t["es"]["Password"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Password"] = "--> Traduction française ici. <--";
$_t["de"]["Password"] = "Passwort";
$_t["pl"]["Password"] = "Has³o";

$_t["en"]["Clear"] = "Clear";
# $_t["es"]["Clear"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Clear"] = "--> Traduction française ici. <--";
$_t["de"]["Clear"] = "Löschen";
$_t["pl"]["Clear"] = "Wyczy¶æ";

$_t["en"]["required"] = "required";
# $_t["es"]["required"] = "--> Traducción española aquí. <--";
# $_t["fr"]["required"] = "--> Traduction française ici. <--";
$_t["de"]["required"] = "erforderlich";
$_t["pl"]["required"] = "wymagane";

$_t["en"]["Email Address"] = "Email Address";
# $_t["es"]["Email Address"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Email Address"] = "--> Traduction française ici. <--";
$_t["de"]["Email Address"] = "Email-Addresse";
$_t["pl"]["Email Address"] = "Adres e-mail";

$_t["en"]["Submit"] = "Submit";
# $_t["es"]["Submit"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Submit"] = "--> Traduction française ici. <--";
$_t["de"]["Submit"] = "Senden";
$_t["pl"]["Submit"] = "Wy¶lij";

$_t["en"]["Reset"] = "Reset";
# $_t["es"]["Reset"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Reset"] = "--> Traduction française ici. <--";
$_t["de"]["Reset"] = "Zurücksetzen";
$_t["pl"]["Reset"] = "Resetuj";

$_t["en"]["Create"] = "Create";
# $_t["es"]["Create"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Create"] = "--> Traduction française ici. <--";
$_t["de"]["Create"] = "Erstellen";
$_t["pl"]["Create"] = "Utwórz";

$_t["en"]["Update"] = "Update";
# $_t["es"]["Update"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Update"] = "--> Traduction française ici. <--";
$_t["de"]["Update"] = "Aktualisiseren";
$_t["pl"]["Update"] = "Aktualizuj";

$_t["en"]["Less"] = "Less";
# $_t["es"]["Less"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Less"] = "--> Traduction française ici. <--";
$_t["de"]["Less"] = "Weniger";
$_t["pl"]["Less"] = "Poprzednie";

$_t["en"]["More"] = "More";
# $_t["es"]["More"] = "--> Traducción española aquí. <--";
# $_t["fr"]["More"] = "--> Traduction française ici. <--";
$_t["de"]["More"] = "Mehr";
$_t["pl"]["More"] = "Nastêpne";

$_t["en"]["Username"] = "Username";
# $_t["es"]["Username"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Username"] = "--> Traduction française ici. <--";
$_t["de"]["Username"] = "Benutzername";
$_t["pl"]["Username"] = "Nazwa u¿ytkownika";

?>
