<?
# INSTRUCTIONS TO TRANSLATORS
#
# This file contains the i18n translations for a subset of the
# Arch Linux User-community Repository (AUR).  This is a PHP
# script, and as such, you MUST pay great attention to the syntax.
# If your text contains any double-quotes ("), you MUST escape
# them with the backslash character (\).
#

include_once("translator.inc");
global $_t;

$_t["en"]["Password"] = "Password";
# $_t["es"]["Password"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Password"] = "--> Traduction française ici. <--";
# $_t["de"]["Password"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Clear"] = "Clear";
# $_t["es"]["Clear"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Clear"] = "--> Traduction française ici. <--";
# $_t["de"]["Clear"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["required"] = "required";
# $_t["es"]["required"] = "--> Traducción española aquí. <--";
# $_t["fr"]["required"] = "--> Traduction française ici. <--";
# $_t["de"]["required"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Email Address"] = "Email Address";
# $_t["es"]["Email Address"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Email Address"] = "--> Traduction française ici. <--";
# $_t["de"]["Email Address"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Submit"] = "Submit";
# $_t["es"]["Submit"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Submit"] = "--> Traduction française ici. <--";
# $_t["de"]["Submit"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Reset"] = "Reset";
# $_t["es"]["Reset"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Reset"] = "--> Traduction française ici. <--";
# $_t["de"]["Reset"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Create"] = "Create";
# $_t["es"]["Create"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Create"] = "--> Traduction française ici. <--";
# $_t["de"]["Create"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Update"] = "Update";
# $_t["es"]["Update"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Update"] = "--> Traduction française ici. <--";
# $_t["de"]["Update"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Less"] = "Less";
# $_t["es"]["Less"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Less"] = "--> Traduction française ici. <--";
# $_t["de"]["Less"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["More"] = "More";
# $_t["es"]["More"] = "--> Traducción española aquí. <--";
# $_t["fr"]["More"] = "--> Traduction française ici. <--";
# $_t["de"]["More"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Username"] = "Username";
# $_t["es"]["Username"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Username"] = "--> Traduction française ici. <--";
# $_t["de"]["Username"] = "--> Deutsche Übersetzung hier. <--";

?>