<?
# INSTRUCTIONS TO TRANSLATORS
#
# This file contains the i18n translations for a subset of the
# Arch Linux User-community Repository (AUR).  This is a PHP
# script, and as such, you MUST pay great attention to the syntax.
# If your text contains any double-quotes ("), you MUST escape
# them with the backslash character (\).
#

include_once("translator.inc");
global $_t;

$_t["en"]["Your session id is invalid."] = "Your session id is invalid.";
# $_t["es"]["Your session id is invalid."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Your session id is invalid."] = "--> Traduction française ici. <--";
# $_t["de"]["Your session id is invalid."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Your session id is invalid."] = "Twój identyfikator sesji jest nieprawid³owy.";

$_t["en"]["If this problem persists, please contact the site administrator."] = "If this problem persists, please contact the site administrator.";
# $_t["es"]["If this problem persists, please contact the site administrator."] = "--> Traducción española aquí. <--";
# $_t["fr"]["If this problem persists, please contact the site administrator."] = "--> Traduction française ici. <--";
# $_t["de"]["If this problem persists, please contact the site administrator."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["If this problem persists, please contact the site administrator."] = "Je¿eli ten problem siê powtarza, skontaktuj siê z administratorem strony.";

?>
