<?
# INSTRUCTIONS TO TRANSLATORS:
# blah blah blah....
	
$_t["en"]["Julie was here!"] = "Julie was here!";
# $_t["es"]["Julie was here!"] = "--> Spanish translation here. <--";
# $_t["fr"]["Julie was here!"] = "--> French translation here. <--";
# $_t["de"]["Julie was here!"] = "--> German translation here. <--";

$_t["en"]["Hello, again!"] = "Hello, again!";
# $_t["es"]["Hello, again!"] = "--> Spanish translation here. <--";
# $_t["fr"]["Hello, again!"] = "--> French translation here. <--";
# $_t["de"]["Hello, again!"] = "--> German translation here. <--";

$_t["en"]["Hello, world!"] = "Hello, world!";
# $_t["es"]["Hello, world!"] = "--> Spanish translation here. <--";
# $_t["fr"]["Hello, world!"] = "--> French translation here. <--";
# $_t["de"]["Hello, world!"] = "--> German translation here. <--";

$_t["en"]["Abernathy was here!"] = "Abernathy was here!";
# $_t["es"]["Abernathy was here!"] = "--> Spanish translation here. <--";
# $_t["fr"]["Abernathy was here!"] = "--> French translation here. <--";
# $_t["de"]["Abernathy was here!"] = "--> German translation here. <--";

?>