<?
# INSTRUCTIONS TO TRANSLATORS
#
# This file contains the i18n translations for a subset of the
# Arch Linux User-community Repository (AUR).  This is a PHP
# script, and as such, you MUST pay great attention to the syntax.
# If your text contains any double-quotes ("), you MUST escape
# them with the backslash character (\).
#

include_once("translator.inc");
global $_t;

$_t["en"]["Hi, this is worth reading!"] = "Hi, this is worth reading!";
# $_t["es"]["Hi, this is worth reading!"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Hi, this is worth reading!"] = "--> Traduction française ici. <--";
# $_t["de"]["Hi, this is worth reading!"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["You must supply a password."] = "You must supply a password.";
# $_t["es"]["You must supply a password."] = "--> Traducción española aquí. <--";
# $_t["fr"]["You must supply a password."] = "--> Traduction française ici. <--";
# $_t["de"]["You must supply a password."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["You must supply a username."] = "You must supply a username.";
# $_t["es"]["You must supply a username."] = "--> Traducción española aquí. <--";
# $_t["fr"]["You must supply a username."] = "--> Traduction française ici. <--";
# $_t["de"]["You must supply a username."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Incorrect password for username %s."] = "Incorrect password for username %s.";
# $_t["es"]["Incorrect password for username %s."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Incorrect password for username %s."] = "--> Traduction française ici. <--";
# $_t["de"]["Incorrect password for username %s."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["After that, this can be filled in with more meaningful text."] = "After that, this can be filled in with more meaningful text.";
# $_t["es"]["After that, this can be filled in with more meaningful text."] = "--> Traducción española aquí. <--";
# $_t["fr"]["After that, this can be filled in with more meaningful text."] = "--> Traduction française ici. <--";
# $_t["de"]["After that, this can be filled in with more meaningful text."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Your account has been suspended."] = "Your account has been suspended.";
# $_t["es"]["Your account has been suspended."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Your account has been suspended."] = "--> Traduction française ici. <--";
# $_t["de"]["Your account has been suspended."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Password:"] = "Password:";
# $_t["es"]["Password:"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Password:"] = "--> Traduction française ici. <--";
# $_t["de"]["Password:"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Username:"] = "Username:";
# $_t["es"]["Username:"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Username:"] = "--> Traduction française ici. <--";
# $_t["de"]["Username:"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["It's more important to get the login functionality finished."] = "It's more important to get the login functionality finished.";
# $_t["es"]["It's more important to get the login functionality finished."] = "--> Traducción española aquí. <--";
# $_t["fr"]["It's more important to get the login functionality finished."] = "--> Traduction française ici. <--";
# $_t["de"]["It's more important to get the login functionality finished."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Currently logged in as: %h%s%h"] = "Currently logged in as: %h%s%h";
# $_t["es"]["Currently logged in as: %h%s%h"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Currently logged in as: %h%s%h"] = "--> Traduction française ici. <--";
# $_t["de"]["Currently logged in as: %h%s%h"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["For now, it's just a place holder."] = "For now, it's just a place holder.";
# $_t["es"]["For now, it's just a place holder."] = "--> Traducción española aquí. <--";
# $_t["fr"]["For now, it's just a place holder."] = "--> Traduction française ici. <--";
# $_t["de"]["For now, it's just a place holder."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["This is where the intro text will go."] = "This is where the intro text will go.";
# $_t["es"]["This is where the intro text will go."] = "--> Traducción española aquí. <--";
# $_t["fr"]["This is where the intro text will go."] = "--> Traduction française ici. <--";
# $_t["de"]["This is where the intro text will go."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Error trying to generate session id."] = "Error trying to generate session id.";
# $_t["es"]["Error trying to generate session id."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Error trying to generate session id."] = "--> Traduction française ici. <--";
# $_t["de"]["Error trying to generate session id."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Login"] = "Login";
# $_t["es"]["Login"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Login"] = "--> Traduction française ici. <--";
# $_t["de"]["Login"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Email Address:"] = "Email Address:";
# $_t["es"]["Email Address:"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Email Address:"] = "--> Traduction française ici. <--";
# $_t["de"]["Email Address:"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["You must supply an email address."] = "You must supply an email address.";
# $_t["es"]["You must supply an email address."] = "--> Traducción española aquí. <--";
# $_t["fr"]["You must supply an email address."] = "--> Traduction française ici. <--";
# $_t["de"]["You must supply an email address."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Incorrect password for email address, %s."] = "Incorrect password for email address, %s.";
# $_t["es"]["Incorrect password for email address, %s."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Incorrect password for email address, %s."] = "--> Traduction française ici. <--";
# $_t["de"]["Incorrect password for email address, %s."] = "--> Deutsche Übersetzung hier. <--";

?>