<?
# INSTRUCTIONS TO TRANSLATORS
#
# This file contains the i18n translations for a subset of the
# Arch Linux User-community Repository (AUR).  This is a PHP
# script, and as such, you MUST pay great attention to the syntax.
# If your text contains any double-quotes ("), you MUST escape
# them with the backslash character (\).
#

include_once("translator.inc");
global $_t;

$_t["en"]["Hi, this is worth reading!"] = "Hi, this is worth reading!";
# $_t["es"]["Hi, this is worth reading!"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Hi, this is worth reading!"] = "--> Traduction française ici. <--";
# $_t["de"]["Hi, this is worth reading!"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Hi, this is worth reading!"] = "Witaj, warto to przeczytaæ!";

$_t["en"]["You must supply a password."] = "You must supply a password.";
# $_t["es"]["You must supply a password."] = "--> Traducción española aquí. <--";
# $_t["fr"]["You must supply a password."] = "--> Traduction française ici. <--";
# $_t["de"]["You must supply a password."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["You must supply a password."] = "Musisz podaæ has³o.";

$_t["en"]["You must supply a username."] = "You must supply a username.";
# $_t["es"]["You must supply a username."] = "--> Traducción española aquí. <--";
# $_t["fr"]["You must supply a username."] = "--> Traduction française ici. <--";
# $_t["de"]["You must supply a username."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["You must supply a username."] = "Musisz podaæ nazwê u¿ytkownika.";

$_t["en"]["Incorrect password for username %s."] = "Incorrect password for username %s.";
# $_t["es"]["Incorrect password for username %s."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Incorrect password for username %s."] = "--> Traduction française ici. <--";
# $_t["de"]["Incorrect password for username %s."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Incorrect password for username %s."] = "Nieprawid³owe has³o dla u¿ytkownika %s.";

$_t["en"]["After that, this can be filled in with more meaningful text."] = "After that, this can be filled in with more meaningful text.";
# $_t["es"]["After that, this can be filled in with more meaningful text."] = "--> Traducción española aquí. <--";
# $_t["fr"]["After that, this can be filled in with more meaningful text."] = "--> Traduction française ici. <--";
# $_t["de"]["After that, this can be filled in with more meaningful text."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["After that, this can be filled in with more meaningful text."] = "Potem mo¿na tu wstawiæ bardziej wyczerpuj±cy tekst.";

$_t["en"]["Your account has been suspended."] = "Your account has been suspended.";
# $_t["es"]["Your account has been suspended."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Your account has been suspended."] = "--> Traduction française ici. <--";
# $_t["de"]["Your account has been suspended."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Your account has been suspended."] = "Twoje konto jest zablokowane.";

$_t["en"]["Password:"] = "Password:";
# $_t["es"]["Password:"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Password:"] = "--> Traduction française ici. <--";
# $_t["de"]["Password:"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Password:"] = "Has³o:";

$_t["en"]["Username:"] = "Username:";
# $_t["es"]["Username:"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Username:"] = "--> Traduction française ici. <--";
# $_t["de"]["Username:"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Username:"] = "Nazwa u¿ytkownika";

$_t["en"]["It's more important to get the login functionality finished."] = "It's more important to get the login functionality finished.";
# $_t["es"]["It's more important to get the login functionality finished."] = "--> Traducción española aquí. <--";
# $_t["fr"]["It's more important to get the login functionality finished."] = "--> Traduction française ici. <--";
# $_t["de"]["It's more important to get the login functionality finished."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["It's more important to get the login functionality finished."] = "Wa¿niejsze jest dokoñczyæ logowanie.";

$_t["en"]["Currently logged in as: %h%s%h"] = "Currently logged in as: %h%s%h";
# $_t["es"]["Currently logged in as: %h%s%h"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Currently logged in as: %h%s%h"] = "--> Traduction française ici. <--";
# $_t["de"]["Currently logged in as: %h%s%h"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Currently logged in as: %h%s%h"] = "Obecnie zalogowany jako: %h%s%h";

$_t["en"]["For now, it's just a place holder."] = "For now, it's just a place holder.";
# $_t["es"]["For now, it's just a place holder."] = "--> Traducción española aquí. <--";
# $_t["fr"]["For now, it's just a place holder."] = "--> Traduction française ici. <--";
# $_t["de"]["For now, it's just a place holder."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["For now, it's just a place holder."] = "Narazie to tylko wype³nia przestrzeñ.";

$_t["en"]["This is where the intro text will go."] = "This is where the intro text will go.";
# $_t["es"]["This is where the intro text will go."] = "--> Traducción española aquí. <--";
# $_t["fr"]["This is where the intro text will go."] = "--> Traduction française ici. <--";
# $_t["de"]["This is where the intro text will go."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["This is where the intro text will go."] = "Tutaj bêdzie tekst powitalny.";

$_t["en"]["Error trying to generate session id."] = "Error trying to generate session id.";
# $_t["es"]["Error trying to generate session id."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Error trying to generate session id."] = "--> Traduction française ici. <--";
# $_t["de"]["Error trying to generate session id."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Error trying to generate session id."] = "B³±d podczas generowania identyfikatora sesji.";

$_t["en"]["Login"] = "Login";
# $_t["es"]["Login"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Login"] = "--> Traduction française ici. <--";
# $_t["de"]["Login"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Login"] = "Zaloguj siê";

$_t["en"]["Email Address:"] = "Email Address:";
# $_t["es"]["Email Address:"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Email Address:"] = "--> Traduction française ici. <--";
# $_t["de"]["Email Address:"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Email Address:"] = "Adres e-mail:";

$_t["en"]["You must supply an email address."] = "You must supply an email address.";
# $_t["es"]["You must supply an email address."] = "--> Traducción española aquí. <--";
# $_t["fr"]["You must supply an email address."] = "--> Traduction française ici. <--";
# $_t["de"]["You must supply an email address."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["You must supply an email address."] = "Musisz podaæ adres e-mail.";

$_t["en"]["Incorrect password for email address, %s."] = "Incorrect password for email address, %s.";
# $_t["es"]["Incorrect password for email address, %s."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Incorrect password for email address, %s."] = "--> Traduction française ici. <--";
# $_t["de"]["Incorrect password for email address, %s."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Incorrect password for email address, %s."] = "Nieprawid³owe has³o dla adresu %s.";

$_t["en"]["Incorrect password for username, %s."] = "Incorrect password for username, %s.";
# $_t["es"]["Incorrect password for username, %s."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Incorrect password for username, %s."] = "--> Traduction française ici. <--";
# $_t["de"]["Incorrect password for username, %s."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Incorrect password for username, %s."] = "Nieprawid³owe has³o dla u¿ytkownika %s.";

$_t["en"]["Logged in as: %h%s%h"] = "Logged in as: %h%s%h";
# $_t["es"]["Logged in as: %h%s%h"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Logged in as: %h%s%h"] = "--> Traduction française ici. <--";
# $_t["de"]["Logged in as: %h%s%h"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Logged in as: %h%s%h"] = "Zalogowany jako: %h%s%h";

$_t["en"]["Logged-in as: %h%s%h"] = "Logged-in as: %h%s%h";
# $_t["es"]["Logged-in as: %h%s%h"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Logged-in as: %h%s%h"] = "--> Traduction française ici. <--";
# $_t["de"]["Logged-in as: %h%s%h"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Logged-in as: %h%s%h"] = "Zalogowany jako: %h%s%h";

$_t["en"]["Error looking up username, %s."] = "Error looking up username, %s.";
# $_t["es"]["Error looking up username, %s."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Error looking up username, %s."] = "--> Traduction française ici. <--";
# $_t["de"]["Error looking up username, %s."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Error looking up username, %s."] = "B³±d podczas wyszukiwania u¿ytkownika %s.";

?>
