<?
# INSTRUCTIONS TO TRANSLATORS
#
# This file contains the i18n translations for a subset of the
# Arch Linux User-community Repository (AUR).  This is a PHP
# script, and as such, you MUST pay great attention to the syntax.
# If your text contains any double-quotes ("), you MUST escape
# them with the backslash character (\).
#

include_once("translator.inc");
global $_t;

$_t["en"]["Under construction..."] = "Under construction...";
# $_t["es"]["Under construction..."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Under construction..."] = "--> Traduction française ici. <--";
# $_t["de"]["Under construction..."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Under construction..."] = "Prace trwają...";

$_t["en"]["Manage package ID: %s"] = "Manage package ID: %s";
# $_t["es"]["Manage package ID: %s"] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Manage package ID: %s"] = "--> Traduction française ici. <--";
# $_t["de"]["Manage package ID: %s"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Manage package ID: %s"] = "Zarządzaj pakietem: %s";

?>
