<?
# INSTRUCTIONS TO TRANSLATORS
#
# This file contains the i18n translations for a subset of the
# Arch Linux User-community Repository (AUR).  This is a PHP
# script, and as such, you MUST pay great attention to the syntax.
# If your text contains any double-quotes ("), you MUST escape
# them with the backslash character (\).
#

include_once("translator.inc");
global $_t;

$_t["en"]["You must be logged in before you can edit package information."] = "You must be logged in before you can edit package information.";
# $_t["es"]["Category"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Category"] = "--> Traduction française ici. <--";
# $_t["de"]["Category"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Missing package ID."] = "Missing package ID.";
# $_t["es"]["Category"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Category"] = "--> Traduction française ici. <--";
# $_t["de"]["Category"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Comment has been deleted."] = "Comment has been deleted.";
# $_t["es"]["Category"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Category"] = "--> Traduction française ici. <--";
# $_t["de"]["Category"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["You are not allowed to delete this comment."] = "You are not allowed to delete this comment.";
# $_t["es"]["Category"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Category"] = "--> Traduction française ici. <--";
# $_t["de"]["Category"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Missing comment ID."] = "Missing comment ID.";
# $_t["es"]["Category"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Category"] = "--> Traduction française ici. <--";
# $_t["de"]["Category"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Comment has been added."] = "Comment has been added.";
# $_t["es"]["Category"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Category"] = "--> Traduction française ici. <--";
# $_t["de"]["Category"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Enter your comment below."] = "Enter your comment below.";
# $_t["es"]["Category"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Category"] = "--> Traduction française ici. <--";
# $_t["de"]["Category"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Submit"] = "Submit";
# $_t["es"]["Category"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Category"] = "--> Traduction française ici. <--";
# $_t["de"]["Category"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Reset"] = "Reset";
# $_t["es"]["Category"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Category"] = "--> Traduction française ici. <--";
# $_t["de"]["Category"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Package category updated."] = "Package category updated.";
# $_t["es"]["Category"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Category"] = "--> Traduction française ici. <--";
# $_t["de"]["Category"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Invalid category ID."] = "Invalid category ID.";
# $_t["es"]["Category"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Category"] = "--> Traduction française ici. <--";
# $_t["de"]["Category"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Select new category"] = "Select new category";
# $_t["es"]["Category"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Category"] = "--> Traduction française ici. <--";
# $_t["de"]["Category"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["You've found a bug if you see this...."] = "You've found a bug if you see this....";
# $_t["es"]["Category"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Category"] = "--> Traduction française ici. <--";
# $_t["de"]["Category"] = "--> Deutsche Übersetzung hier. <--";

?>
