<?
# INSTRUCTIONS TO TRANSLATORS
#
# This file contains the i18n translations for a subset of the
# Arch Linux User-community Repository (AUR).  This is a PHP
# script, and as such, you MUST pay great attention to the syntax.
# If your text contains any double-quotes ("), you MUST escape
# them with the backslash character (\).
#

include_once("translator.inc");
global $_t;

$_t["en"]["Go back to %hpackage details view%h."] = "Go back to %hpackage details view%h.";
# $_t["es"]["Category"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Category"] = "--> Traduction française ici. <--";
# $_t["de"]["Category"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Go back to %hpackage details view%h."] = "Powrót do %hinformacji o pakiecie%h.";

$_t["en"]["None"] = "None";
# $_t["es"]["Category"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Category"] = "--> Traduction française ici. <--";
# $_t["de"]["Category"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["None"] = "Brak";

$_t["en"]["change category"] = "change category";
# $_t["es"]["Category"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Category"] = "--> Traduction française ici. <--";
# $_t["de"]["Category"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["change category"] = "zmieñ kategoriê";

$_t["en"]["Delete comment"] = "Delete comment";
# $_t["es"]["Category"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Category"] = "--> Traduction française ici. <--";
# $_t["de"]["Category"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Delete comment"] = "Usuñ komentarz";

$_t["en"]["Comment by: %h%s%h on %h%s%h"] = "Comment by: %h%s%h on %h%s%h";
# $_t["es"]["Category"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Category"] = "--> Traduction française ici. <--";
# $_t["de"]["Category"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Comment by: %h%s%h on %h%s%h"] = "Komentarz - autor: %h%s%h, data: %h%s%h";

$_t["en"]["Add Comment"] = "Add Comment";
# $_t["es"]["Category"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Category"] = "--> Traduction française ici. <--";
# $_t["de"]["Category"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Add Comment"] = "Dodaj komentarz";

$_t["en"]["Comments"] = "Comments";
# $_t["es"]["Category"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Category"] = "--> Traduction française ici. <--";
# $_t["de"]["Category"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Comments"] = "Komentarze";

$_t["en"]["Sources"] = "Sources";
# $_t["es"]["Category"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Category"] = "--> Traduction française ici. <--";
# $_t["de"]["Category"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Sources"] = "¬ród³a";

$_t["en"]["Dependencies"] = "Dependencies";
# $_t["es"]["Category"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Category"] = "--> Traduction française ici. <--";
# $_t["de"]["Category"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Dependencies"] = "Zale¿no¶ci";

$_t["en"]["Package Details"] = "Package Details";
# $_t["es"]["Category"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Category"] = "--> Traduction française ici. <--";
# $_t["de"]["Category"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Package Details"] = "Informacje o pakiecie";

$_t["en"]["Category"] = "Category";
# $_t["es"]["Category"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Category"] = "--> Traduction française ici. <--";
# $_t["de"]["Category"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Category"] = "Kategoria";

$_t["en"]["Maintainer"] = "Maintainer";
# $_t["es"]["Maintainer"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Maintainer"] = "--> Traduction française ici. <--";
# $_t["de"]["Maintainer"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Maintainer"] = "Opiekun";

$_t["en"]["Name"] = "Name";
# $_t["es"]["Name"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Name"] = "--> Traduction française ici. <--";
# $_t["de"]["Name"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Name"] = "Nazwa";

$_t["en"]["Per page"] = "Per page";
# $_t["es"]["Per page"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Per page"] = "--> Traduction française ici. <--";
# $_t["de"]["Per page"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Per page"] = "Na stronie";

$_t["en"]["Popularity"] = "Popularity";
# $_t["es"]["Popularity"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Popularity"] = "--> Traduction française ici. <--";
# $_t["de"]["Popularity"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Popularity"] = "Popularno¶æ";

$_t["en"]["Sort by"] = "Sort by";
# $_t["es"]["Sort by"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Sort by"] = "--> Traduction française ici. <--";
# $_t["de"]["Sort by"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Sort by"] = "Sortuj wed³ug";

$_t["en"]["Search Criteria"] = "Search Criteria";
# $_t["es"]["Search Criteria"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Search Criteria"] = "--> Traduction française ici. <--";
# $_t["de"]["Search Criteria"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Search Criteria"] = "Kryteria wyszukiwania";

$_t["en"]["Location"] = "Location";
# $_t["es"]["Location"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Location"] = "--> Traduction française ici. <--";
# $_t["de"]["Location"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Location"] = "Lokacja";

$_t["en"]["Keywords"] = "Keywords";
# $_t["es"]["Keywords"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Keywords"] = "--> Traduction française ici. <--";
# $_t["de"]["Keywords"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Keywords"] = "S³owa kluczowe";

$_t["en"]["Any"] = "Any";
# $_t["es"]["Any"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Any"] = "--> Traduction française ici. <--";
# $_t["de"]["Any"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Any"] = "Dowolna";

$_t["en"]["Votes"] = "Votes";
# $_t["es"]["Votes"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Votes"] = "--> Traduction française ici. <--";
# $_t["de"]["Votes"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Votes"] = "G³osów";

$_t["en"]["Description"] = "Description";
# $_t["es"]["Description"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Description"] = "--> Traduction française ici. <--";
# $_t["de"]["Description"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Description"] = "Opis";

$_t["en"]["No packages matched your search criteria."] = "No packages matched your search criteria.";
# $_t["es"]["No packages matched your search criteria."] = "--> Traducción española aquí. <--";
# $_t["fr"]["No packages matched your search criteria."] = "--> Traduction française ici. <--";
# $_t["de"]["No packages matched your search criteria."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["No packages matched your search criteria."] = "¯aden pakiet nie spe³nia podanych kryteriów.";

$_t["en"]["My Packages"] = "My Packages";
# $_t["es"]["My Packages"] = "--> Traducción española aquí. <--";
# $_t["fr"]["My Packages"] = "--> Traduction française ici. <--";
# $_t["de"]["My Packages"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["My Packages"] = "Moje pakiety";

$_t["en"]["Go"] = "Go";
# $_t["es"]["Go"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Go"] = "--> Traduction française ici. <--";
# $_t["de"]["Go"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Go"] = "Szukaj";

$_t["en"]["Out-of-date"] = "Out-of-date";
# $_t["es"]["Out-of-date"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Out-of-date"] = "--> Traduction française ici. <--";
# $_t["de"]["Out-of-date"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Out-of-date"] = "Nieaktualny";

$_t["en"]["Flag Out-of-date"] = "Flag Out-of-date";
# $_t["es"]["Flag Out-of-date"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Flag Out-of-date"] = "--> Traduction française ici. <--";
# $_t["de"]["Flag Out-of-date"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Flag Out-of-date"] = "Zaznacz jako nieaktualny";

$_t["en"]["Actions"] = "Actions";
# $_t["es"]["Actions"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Actions"] = "--> Traduction française ici. <--";
# $_t["de"]["Actions"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Actions"] = "Dzia³ania";

$_t["en"]["Adopt Packages"] = "Adopt Packages";
# $_t["es"]["Adopt Packages"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Adopt Packages"] = "--> Traduction française ici. <--";
# $_t["de"]["Adopt Packages"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Adopt Packages"] = "Przejmij pakiety";

$_t["en"]["Disown Packages"] = "Disown Packages";
# $_t["es"]["Disown Packages"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Disown Packages"] = "--> Traduction française ici. <--";
# $_t["de"]["Disown Packages"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Disown Packages"] = "Porzuæ pakiety";

$_t["en"]["Delete Packages"] = "Delete Packages";
# $_t["es"]["Delete Packages"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Delete Packages"] = "--> Traduction française ici. <--";
# $_t["de"]["Delete Packages"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Delete Packages"] = "Usuñ pakiety";

$_t["en"]["You did not select any packages to delete."] = "You did not select any packages to delete.";
$_t["pl"]["You did not select any packages to delete."] = "Nie wybra³e¶ ¿adnych pakietów do usuniêcia.";

$_t["en"]["None of the selected packages could be deleted."] = "None of the selected packages could be deleted.";
$_t["pl"]["None of the selected packages could be deleted."] = "¯aden z wybranych pakietów nie móg³ byæ usuniêty.";

$_t["en"]["The selected packages have been deleted."] = "The selected packages have been deleted.";
$_t["pl"]["The selected packages have been deleted."] = "Wybrane pakiety zosta³y usuniête.";

$_t["en"]["Vote"] = "Vote";
# $_t["es"]["Vote"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Vote"] = "--> Traduction française ici. <--";
# $_t["de"]["Vote"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Vote"] = "G³osuj";

$_t["en"]["Error retrieving package details."] = "Error retrieving package details.";
# $_t["es"]["Error retrieving package details."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Error retrieving package details."] = "--> Traduction française ici. <--";
# $_t["de"]["Error retrieving package details."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Error retrieving package details."] = "B³±d podczas pobierania informacji o pakiecie.";

$_t["en"]["Package details could not be found."] = "Package details could not be found.";
# $_t["es"]["Package details could not be found."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Package details could not be found."] = "--> Traduction française ici. <--";
# $_t["de"]["Package details could not be found."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Package details could not be found."] = "Nie odnaleziono informacji o pakiecie.";

$_t["en"]["Error retrieving package list."] = "Error retrieving package list.";
# $_t["es"]["Error retrieving package list."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Error retrieving package list."] = "--> Traduction française ici. <--";
# $_t["de"]["Error retrieving package list."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Error retrieving package list."] = "B³±d podczas pobierania listy pakietów.";

$_t["en"]["Go back to %hsearch results%h."] = "Go back to %hsearch results%h.";
# $_t["es"]["Go back to %hsearch results%h."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Go back to %hsearch results%h."] = "--> Traduction française ici. <--";
# $_t["de"]["Go back to %hsearch results%h."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Go back to %hsearch results%h."] = "Powrót do wyników wyszukiwania.";

$_t["en"]["Manage"] = "Manage";
# $_t["es"]["Manage"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Manage"] = "--> Traduction française ici. <--";
# $_t["de"]["Manage"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Manage"] = "Zarz±dzaj";

$_t["en"]["Un-flag Out-of-date"] = "Un-flag Out-of-date";
# $_t["es"]["Un-flag Out-of-date"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Un-flag Out-of-date"] = "--> Traduction française ici. <--";
# $_t["de"]["Un-flag Out-of-date"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Un-flag Out-of-date"] = "Usuñ flagê nieaktualno¶ci";

$_t["en"]["Unflag Out-of-date"] = "Unflag Out-of-date";
# $_t["es"]["Unflag Out-of-date"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Unflag Out-of-date"] = "--> Traduction française ici. <--";
# $_t["de"]["Unflag Out-of-date"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Unflag Out-of-date"] = "Usuñ flagê nieaktualno¶ci";

$_t["en"]["Un-Vote"] = "Un-Vote";
# $_t["es"]["Un-Vote"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Un-Vote"] = "--> Traduction française ici. <--";
# $_t["de"]["Un-Vote"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Un-Vote"] = "Anuluj g³os";

$_t["en"]["Yes"] = "Yes";
# $_t["es"]["Yes"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Yes"] = "--> Traduction française ici. <--";
# $_t["de"]["Yes"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Yes"] = "Tak";

$_t["en"]["Orphans"] = "Orphans";
# $_t["es"]["Orphans"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Orphans"] = "--> Traduction française ici. <--";
# $_t["de"]["Orphans"] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Orphans"] = "Bez opiekuna";

?>
