<?
# INSTRUCTIONS TO TRANSLATORS
#
# This file contains the i18n translations for a subset of the
# Arch Linux User-community Repository (AUR).  This is a PHP
# script, and as such, you MUST pay great attention to the syntax.
# If your text contains any double-quotes ("), you MUST escape
# them with the backslash character (\).
#

include_once("translator.inc");
global $_t;

$_t["en"]["Category"] = "Category";
# $_t["es"]["Category"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Category"] = "--> Traduction française ici. <--";
# $_t["de"]["Category"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Maintainer"] = "Maintainer";
# $_t["es"]["Maintainer"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Maintainer"] = "--> Traduction française ici. <--";
# $_t["de"]["Maintainer"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Name"] = "Name";
# $_t["es"]["Name"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Name"] = "--> Traduction française ici. <--";
# $_t["de"]["Name"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Per page"] = "Per page";
# $_t["es"]["Per page"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Per page"] = "--> Traduction française ici. <--";
# $_t["de"]["Per page"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Popularity"] = "Popularity";
# $_t["es"]["Popularity"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Popularity"] = "--> Traduction française ici. <--";
# $_t["de"]["Popularity"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Sort by"] = "Sort by";
# $_t["es"]["Sort by"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Sort by"] = "--> Traduction française ici. <--";
# $_t["de"]["Sort by"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Search Criteria"] = "Search Criteria";
# $_t["es"]["Search Criteria"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Search Criteria"] = "--> Traduction française ici. <--";
# $_t["de"]["Search Criteria"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Location"] = "Location";
# $_t["es"]["Location"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Location"] = "--> Traduction française ici. <--";
# $_t["de"]["Location"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Keywords"] = "Keywords";
# $_t["es"]["Keywords"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Keywords"] = "--> Traduction française ici. <--";
# $_t["de"]["Keywords"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Any"] = "Any";
# $_t["es"]["Any"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Any"] = "--> Traduction française ici. <--";
# $_t["de"]["Any"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Votes"] = "Votes";
# $_t["es"]["Votes"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Votes"] = "--> Traduction française ici. <--";
# $_t["de"]["Votes"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Description"] = "Description";
# $_t["es"]["Description"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Description"] = "--> Traduction française ici. <--";
# $_t["de"]["Description"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["No packages matched your search criteria."] = "No packages matched your search criteria.";
# $_t["es"]["No packages matched your search criteria."] = "--> Traducción española aquí. <--";
# $_t["fr"]["No packages matched your search criteria."] = "--> Traduction française ici. <--";
# $_t["de"]["No packages matched your search criteria."] = "--> Deutsche Übersetzung hier. <--";

?>