<?
# INSTRUCTIONS TO TRANSLATORS
#
# This file contains the i18n translations for a subset of the
# Arch Linux User-community Repository (AUR).  This is a PHP
# script, and as such, you MUST pay great attention to the syntax.
# If your text contains any double-quotes ("), you MUST escape
# them with the backslash character (\).
#

include_once("translator.inc");
global $_t;

$_t["en"]["Under construction..."] = "Under construction...";
# $_t["es"]["Under construction..."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Under construction..."] = "--> Traduction française ici. <--";
# $_t["de"]["Under construction..."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Under construction..."] = "Prace trwają...";

$_t["en"]["You must be logged in before you can vote for packages."] = "You must be logged in before you can vote for packages.";
# $_t["es"]["You must be logged in before you can vote for packages."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["You must be logged in before you can vote for packages."] = "--> Traduction française ici. <--";
# $_t["de"]["You must be logged in before you can vote for packages."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["You must be logged in before you can vote for packages."] = "Musisz być zalogowany aby móc głosować na pakiety.";

$_t["en"]["You do not have access to disown packages."] = "You do not have access to disown packages.";
# $_t["es"]["You do not have access to disown packages."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["You do not have access to disown packages."] = "--> Traduction française ici. <--";
# $_t["de"]["You do not have access to disown packages."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["You do not have access to disown packages."] = "Nie masz uprawnień do porzucania pakietów.";

$_t["en"]["You must be logged in before you can flag packages."] = "You must be logged in before you can flag packages.";
# $_t["es"]["You must be logged in before you can flag packages."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["You must be logged in before you can flag packages."] = "--> Traduction française ici. <--";
# $_t["de"]["You must be logged in before you can flag packages."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["You must be logged in before you can flag packages."] = "Musisz być zalogowany aby móc zmieniać flagi pakietów.";

$_t["en"]["You do not have access to adopt packages."] = "You do not have access to adopt packages.";
# $_t["es"]["You do not have access to adopt packages."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["You do not have access to adopt packages."] = "--> Traduction française ici. <--";
# $_t["de"]["You do not have access to adopt packages."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["You do not have access to adopt packages."] = "Nie masz uprawnień do przejmowania pakietów.";

$_t["en"]["You must be logged in before you can disown packages."] = "You must be logged in before you can disown packages.";
# $_t["es"]["You must be logged in before you can disown packages."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["You must be logged in before you can disown packages."] = "--> Traduction française ici. <--";
# $_t["de"]["You must be logged in before you can disown packages."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["You must be logged in before you can disown packages."] = "Musisz być zalogowany aby móc porzucać pakiety.";

$_t["en"]["Error trying to retrieve package details."] = "Error trying to retrieve package details.";
# $_t["es"]["Error trying to retrieve package details."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Error trying to retrieve package details."] = "--> Traduction française ici. <--";
# $_t["de"]["Error trying to retrieve package details."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Error trying to retrieve package details."] = "Błąd podczas pobierania informacji o pakiecie.";

$_t["en"]["You must be logged in before you can adopt packages."] = "You must be logged in before you can adopt packages.";
# $_t["es"]["You must be logged in before you can adopt packages."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["You must be logged in before you can adopt packages."] = "--> Traduction française ici. <--";
# $_t["de"]["You must be logged in before you can adopt packages."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["You must be logged in before you can adopt packages."] = "Musisz być zalogowany aby móc przejmować pakiety.";

$_t["en"]["The selected packages have been flagged out-of-date."] = "The selected packages have been flagged out-of-date.";
# $_t["es"]["The selected packages have been flagged out-of-date."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["The selected packages have been flagged out-of-date."] = "--> Traduction française ici. <--";
# $_t["de"]["The selected packages have been flagged out-of-date."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["The selected packages have been flagged out-of-date."] = "Wybrane pakiety zostały zaznaczone jako nieaktualne.";

$_t["en"]["You did not select any packages to flag."] = "You did not select any packages to flag.";
# $_t["es"]["You did not select any packages to flag."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["You did not select any packages to flag."] = "--> Traduction française ici. <--";
# $_t["de"]["You did not select any packages to flag."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["You did not select any packages to flag."] = "Nie wybrałeś żadnych pakietów do zaznaczenia.";

$_t["en"]["The selected packages have been unflagged."] = "The selected packages have been unflagged.";
# $_t["es"]["The selected packages have been unflagged."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["The selected packages have been unflagged."] = "--> Traduction française ici. <--";
# $_t["de"]["The selected packages have been unflagged."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["The selected packages have been unflagged."] = "Wybrane pakiety zostały odznaczone.";

$_t["en"]["You must be logged in before you can unflag packages."] = "You must be logged in before you can unflag packages.";
# $_t["es"]["You must be logged in before you can unflag packages."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["You must be logged in before you can unflag packages."] = "--> Traduction française ici. <--";
# $_t["de"]["You must be logged in before you can unflag packages."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["You must be logged in before you can unflag packages."] = "Musisz być zalogowany aby móc odznaczać pakiety.";

$_t["en"]["You did not select any packages to unflag."] = "You did not select any packages to unflag.";
# $_t["es"]["You did not select any packages to unflag."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["You did not select any packages to unflag."] = "--> Traduction française ici. <--";
# $_t["de"]["You did not select any packages to unflag."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["You did not select any packages to unflag."] = "Nie wybrałeś żadnych pakietów do odznaczenia.";

$_t["en"]["You did not select any packages to adopt."] = "You did not select any packages to adopt.";
# $_t["es"]["You did not select any packages to adopt."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["You did not select any packages to adopt."] = "--> Traduction française ici. <--";
# $_t["de"]["You did not select any packages to adopt."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["You did not select any packages to adopt."] = "Nie wybrałeś żadnych pakietów do przejęcia.";

$_t["en"]["You did not select any packages to disowned."] = "You did not select any packages to disowned.";
# $_t["es"]["You did not select any packages to disowned."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["You did not select any packages to disowned."] = "--> Traduction française ici. <--";
# $_t["de"]["You did not select any packages to disowned."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["You did not select any packages to disowned."] = "Nie wybrałeś żadnych pakietów do porzucenia.";

$_t["en"]["The selected packages have been adopted."] = "The selected packages have been adopted.";
# $_t["es"]["The selected packages have been adopted."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["The selected packages have been adopted."] = "--> Traduction française ici. <--";
# $_t["de"]["The selected packages have been adopted."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["The selected packages have been adopted."] = "Wybrane pakiety zostały przejęte.";

$_t["en"]["The selected packages have been disowned."] = "The selected packages have been disowned.";
# $_t["es"]["The selected packages have been disowned."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["The selected packages have been disowned."] = "--> Traduction française ici. <--";
# $_t["de"]["The selected packages have been disowned."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["The selected packages have been disowned."] = "Wybrane pakiety zostały porzucone.";

$_t["en"]["You must be logged in before you can un-vote for packages."] = "You must be logged in before you can un-vote for packages.";
# $_t["es"]["You must be logged in before you can un-vote for packages."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["You must be logged in before you can un-vote for packages."] = "--> Traduction française ici. <--";
# $_t["de"]["You must be logged in before you can un-vote for packages."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["You must be logged in before you can un-vote for packages."] = "Musisz być zalogowany aby móc anulować głosy na pakiety.";

$_t["en"]["Your votes have been removed from the selected packages."] = "Your votes have been removed from the selected packages.";
# $_t["es"]["Your votes have been removed from the selected packages."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Your votes have been removed from the selected packages."] = "--> Traduction française ici. <--";
# $_t["de"]["Your votes have been removed from the selected packages."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Your votes have been removed from the selected packages."] = "Twoje głosy zostały odebrane wybranym pakietom.";

$_t["en"]["You did not select any packages to vote for."] = "You did not select any packages to vote for.";
# $_t["es"]["You did not select any packages to vote for."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["You did not select any packages to vote for."] = "--> Traduction française ici. <--";
# $_t["de"]["You did not select any packages to vote for."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["You did not select any packages to vote for."] = "Nie wybrałeś żadnych pakietów do oddania głosów.";

$_t["en"]["You did not select any packages to un-vote for."] = "You did not select any packages to un-vote for.";
# $_t["es"]["You did not select any packages to un-vote for."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["You did not select any packages to un-vote for."] = "--> Traduction française ici. <--";
# $_t["de"]["You did not select any packages to un-vote for."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["You did not select any packages to un-vote for."] = "Nie wybrałeś żadnych pakietów do anulowania głosów.";

$_t["en"]["Your votes have been cast for the selected packages."] = "Your votes have been cast for the selected packages.";
# $_t["es"]["Your votes have been cast for the selected packages."] = "--> Traducción espańola aquí. <--";
# $_t["fr"]["Your votes have been cast for the selected packages."] = "--> Traduction française ici. <--";
# $_t["de"]["Your votes have been cast for the selected packages."] = "--> Deutsche Übersetzung hier. <--";
$_t["pl"]["Your votes have been cast for the selected packages."] = "Twoje głosy zostały przyznane wybranym pakietom.";

?>
