<?
# INSTRUCTIONS TO TRANSLATORS
#
# This file contains the i18n translations for a subset of the
# Arch Linux User-community Repository (AUR).  This is a PHP
# script, and as such, you MUST pay great attention to the syntax.
# If your text contains any double-quotes ("), you MUST escape
# them with the backslash character (\).
#

include_once("translator.inc");
global $_t;

$_t["en"]["Under construction..."] = "Under construction...";
# $_t["es"]["Under construction..."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Under construction..."] = "--> Traduction française ici. <--";
# $_t["de"]["Under construction..."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["You must be logged in before you can vote for packages."] = "You must be logged in before you can vote for packages.";
# $_t["es"]["You must be logged in before you can vote for packages."] = "--> Traducción española aquí. <--";
# $_t["fr"]["You must be logged in before you can vote for packages."] = "--> Traduction française ici. <--";
# $_t["de"]["You must be logged in before you can vote for packages."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["You do not have access to disown packages."] = "You do not have access to disown packages.";
# $_t["es"]["You do not have access to disown packages."] = "--> Traducción española aquí. <--";
# $_t["fr"]["You do not have access to disown packages."] = "--> Traduction française ici. <--";
# $_t["de"]["You do not have access to disown packages."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["You must be logged in before you can flag packages."] = "You must be logged in before you can flag packages.";
# $_t["es"]["You must be logged in before you can flag packages."] = "--> Traducción española aquí. <--";
# $_t["fr"]["You must be logged in before you can flag packages."] = "--> Traduction française ici. <--";
# $_t["de"]["You must be logged in before you can flag packages."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["You do not have access to adopt packages."] = "You do not have access to adopt packages.";
# $_t["es"]["You do not have access to adopt packages."] = "--> Traducción española aquí. <--";
# $_t["fr"]["You do not have access to adopt packages."] = "--> Traduction française ici. <--";
# $_t["de"]["You do not have access to adopt packages."] = "--> Deutsche Übersetzung hier. <--";

?>