<?
# INSTRUCTIONS TO TRANSLATORS
#
# This file contains the i18n translations for a subset of the
# Arch Linux User-community Repository (AUR).  This is a PHP
# script, and as such, you MUST pay great attention to the syntax.
# If your text contains any double-quotes ("), you MUST escape
# them with the backslash character (\).
#

include_once("translator.inc");
global $_t;

$_t["en"]["Under construction..."] = "Under construction...";
# $_t["es"]["Under construction..."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Under construction..."] = "--> Traduction française ici. <--";
# $_t["de"]["Under construction..."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Sorry, uploads are not permitted by this server."] = "Sorry, uploads are not permitted by this server.";
# $_t["es"]["Sorry, uploads are not permitted by this server."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Sorry, uploads are not permitted by this server."] = "--> Traduction française ici. <--";
# $_t["de"]["Sorry, uploads are not permitted by this server."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["You must create an account before you can upload packages."] = "You must create an account before you can upload packages.";
# $_t["es"]["You must create an account before you can upload packages."] = "--> Traducción española aquí. <--";
# $_t["fr"]["You must create an account before you can upload packages."] = "--> Traduction française ici. <--";
# $_t["de"]["You must create an account before you can upload packages."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Upload package"] = "Upload package";
# $_t["es"]["Upload package"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Upload package"] = "--> Traduction française ici. <--";
# $_t["de"]["Upload package"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Upload"] = "Upload";
# $_t["es"]["Upload"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Upload"] = "--> Traduction française ici. <--";
# $_t["de"]["Upload"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["No"] = "No";
# $_t["es"]["No"] = "--> Traducción española aquí. <--";
# $_t["fr"]["No"] = "--> Traduction française ici. <--";
# $_t["de"]["No"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Error trying to upload file - please try again."] = "Error trying to upload file - please try again.";
# $_t["es"]["Error trying to upload file - please try again."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Error trying to upload file - please try again."] = "--> Traduction française ici. <--";
# $_t["de"]["Error trying to upload file - please try again."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Yes"] = "Yes";
# $_t["es"]["Yes"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Yes"] = "--> Traduction française ici. <--";
# $_t["de"]["Yes"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Overwrite existing package?"] = "Overwrite existing package?";
# $_t["es"]["Overwrite existing package?"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Overwrite existing package?"] = "--> Traduction française ici. <--";
# $_t["de"]["Overwrite existing package?"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Missing build function in PKGBUILD."] = "Missing build function in PKGBUILD.";
# $_t["es"]["Missing build function in PKGBUILD."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Missing build function in PKGBUILD."] = "--> Traduction française ici. <--";
# $_t["de"]["Missing build function in PKGBUILD."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Could not create incoming directory: %s."] = "Could not create incoming directory: %s.";
# $_t["es"]["Could not create incoming directory: %s."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Could not create incoming directory: %s."] = "--> Traduction française ici. <--";
# $_t["de"]["Could not create incoming directory: %s."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Comments"] = "Comments";
# $_t["es"]["Comments"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Comments"] = "--> Traduction française ici. <--";
# $_t["de"]["Comments"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Missing pkgdesc variable in PKGBUILD."] = "Missing pkgdesc variable in PKGBUILD.";
# $_t["es"]["Missing pkgdesc variable in PKGBUILD."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Missing pkgdesc variable in PKGBUILD."] = "--> Traduction française ici. <--";
# $_t["de"]["Missing pkgdesc variable in PKGBUILD."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Error exec'ing the mv command."] = "Error exec'ing the mv command.";
# $_t["es"]["Error exec'ing the mv command."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Error exec'ing the mv command."] = "--> Traduction française ici. <--";
# $_t["de"]["Error exec'ing the mv command."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["You did not specify a package name."] = "You did not specify a package name.";
# $_t["es"]["You did not specify a package name."] = "--> Traducción española aquí. <--";
# $_t["fr"]["You did not specify a package name."] = "--> Traduction française ici. <--";
# $_t["de"]["You did not specify a package name."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Error trying to unpack upload - PKGBUILD does not exist."] = "Error trying to unpack upload - PKGBUILD does not exist.";
# $_t["es"]["Error trying to unpack upload - PKGBUILD does not exist."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Error trying to unpack upload - PKGBUILD does not exist."] = "--> Traduction française ici. <--";
# $_t["de"]["Error trying to unpack upload - PKGBUILD does not exist."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["You are not allowed to overwrite the %h%s%h package."] = "You are not allowed to overwrite the %h%s%h package.";
# $_t["es"]["You are not allowed to overwrite the %h%s%h package."] = "--> Traducción española aquí. <--";
# $_t["fr"]["You are not allowed to overwrite the %h%s%h package."] = "--> Traduction française ici. <--";
# $_t["de"]["You are not allowed to overwrite the %h%s%h package."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Upload package file"] = "Upload package file";
# $_t["es"]["Upload package file"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Upload package file"] = "--> Traduction française ici. <--";
# $_t["de"]["Upload package file"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Missing url variable in PKGBUILD."] = "Missing url variable in PKGBUILD.";
# $_t["es"]["Missing url variable in PKGBUILD."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Missing url variable in PKGBUILD."] = "--> Traduction française ici. <--";
# $_t["de"]["Missing url variable in PKGBUILD."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Missing pkgver variable in PKGBUILD."] = "Missing pkgver variable in PKGBUILD.";
# $_t["es"]["Missing pkgver variable in PKGBUILD."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Missing pkgver variable in PKGBUILD."] = "--> Traduction française ici. <--";
# $_t["de"]["Missing pkgver variable in PKGBUILD."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Could not change to directory %s."] = "Could not change to directory %s.";
# $_t["es"]["Could not change to directory %s."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Could not change to directory %s."] = "--> Traduction française ici. <--";
# $_t["de"]["Could not change to directory %s."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["You did not tag the 'overwrite' checkbox."] = "You did not tag the 'overwrite' checkbox.";
# $_t["es"]["You did not tag the 'overwrite' checkbox."] = "--> Traducción española aquí. <--";
# $_t["fr"]["You did not tag the 'overwrite' checkbox."] = "--> Traduction française ici. <--";
# $_t["de"]["You did not tag the 'overwrite' checkbox."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Could not change directory to %s."] = "Could not change directory to %s.";
# $_t["es"]["Could not change directory to %s."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Could not change directory to %s."] = "--> Traduction française ici. <--";
# $_t["de"]["Could not change directory to %s."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Invalid name: only lowercase letters are allowed."] = "Invalid name: only lowercase letters are allowed.";
# $_t["es"]["Invalid name: only lowercase letters are allowed."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Invalid name: only lowercase letters are allowed."] = "--> Traduction française ici. <--";
# $_t["de"]["Invalid name: only lowercase letters are allowed."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Package names do not match."] = "Package names do not match.";
# $_t["es"]["Package names do not match."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Package names do not match."] = "--> Traduction française ici. <--";
# $_t["de"]["Package names do not match."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Package name"] = "Package name";
# $_t["es"]["Package name"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Package name"] = "--> Traduction française ici. <--";
# $_t["de"]["Package name"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Missing md5sums variable in PKGBUILD."] = "Missing md5sums variable in PKGBUILD.";
# $_t["es"]["Missing md5sums variable in PKGBUILD."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Missing md5sums variable in PKGBUILD."] = "--> Traduction française ici. <--";
# $_t["de"]["Missing md5sums variable in PKGBUILD."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Missing pkgrel variable in PKGBUILD."] = "Missing pkgrel variable in PKGBUILD.";
# $_t["es"]["Missing pkgrel variable in PKGBUILD."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Missing pkgrel variable in PKGBUILD."] = "--> Traduction française ici. <--";
# $_t["de"]["Missing pkgrel variable in PKGBUILD."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Missing pkgname variable in PKGBUILD."] = "Missing pkgname variable in PKGBUILD.";
# $_t["es"]["Missing pkgname variable in PKGBUILD."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Missing pkgname variable in PKGBUILD."] = "--> Traduction française ici. <--";
# $_t["de"]["Missing pkgname variable in PKGBUILD."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Could not create directory %s."] = "Could not create directory %s.";
# $_t["es"]["Could not create directory %s."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Could not create directory %s."] = "--> Traduction française ici. <--";
# $_t["de"]["Could not create directory %s."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Unknown file format for uploaded file."] = "Unknown file format for uploaded file.";
# $_t["es"]["Unknown file format for uploaded file."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Unknown file format for uploaded file."] = "--> Traduction française ici. <--";
# $_t["de"]["Unknown file format for uploaded file."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Missing source variable in PKGBUILD."] = "Missing source variable in PKGBUILD.";
# $_t["es"]["Missing source variable in PKGBUILD."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Missing source variable in PKGBUILD."] = "--> Traduction française ici. <--";
# $_t["de"]["Missing source variable in PKGBUILD."] = "--> Deutsche Übersetzung hier. <--";

?>