<?
# INSTRUCTIONS TO TRANSLATORS
#
# This file contains the i18n translations for a subset of the
# Arch Linux User-community Repository (AUR).  This is a PHP
# script, and as such, you MUST pay great attention to the syntax.
# If your text contains any double-quotes ("), you MUST escape
# them with the backslash character (\).
#

include_once("translator.inc");
global $_t;

$_t["en"]["Under construction..."] = "Under construction...";
# $_t["es"]["Under construction..."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Under construction..."] = "--> Traduction française ici. <--";
# $_t["de"]["Under construction..."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Sorry, uploads are not permitted by this server."] = "Sorry, uploads are not permitted by this server.";
# $_t["es"]["Sorry, uploads are not permitted by this server."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Sorry, uploads are not permitted by this server."] = "--> Traduction française ici. <--";
# $_t["de"]["Sorry, uploads are not permitted by this server."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["You must create an account before you can upload packages."] = "You must create an account before you can upload packages.";
# $_t["es"]["You must create an account before you can upload packages."] = "--> Traducción española aquí. <--";
# $_t["fr"]["You must create an account before you can upload packages."] = "--> Traduction française ici. <--";
# $_t["de"]["You must create an account before you can upload packages."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Upload package"] = "Upload package";
# $_t["es"]["Upload package"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Upload package"] = "--> Traduction française ici. <--";
# $_t["de"]["Upload package"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Upload"] = "Upload";
# $_t["es"]["Upload"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Upload"] = "--> Traduction française ici. <--";
# $_t["de"]["Upload"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["No"] = "No";
# $_t["es"]["No"] = "--> Traducción española aquí. <--";
# $_t["fr"]["No"] = "--> Traduction française ici. <--";
# $_t["de"]["No"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Error trying to upload file - please try again."] = "Error trying to upload file - please try again.";
# $_t["es"]["Error trying to upload file - please try again."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Error trying to upload file - please try again."] = "--> Traduction française ici. <--";
# $_t["de"]["Error trying to upload file - please try again."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Yes"] = "Yes";
# $_t["es"]["Yes"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Yes"] = "--> Traduction française ici. <--";
# $_t["de"]["Yes"] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Overwrite existing package?"] = "Overwrite existing package?";
# $_t["es"]["Overwrite existing package?"] = "--> Traducción española aquí. <--";
# $_t["fr"]["Overwrite existing package?"] = "--> Traduction française ici. <--";
# $_t["de"]["Overwrite existing package?"] = "--> Deutsche Übersetzung hier. <--";

?>