<?
# INSTRUCTIONS TO TRANSLATORS
#
# This file contains the i18n translations for a subset of the
# Arch Linux User-community Repository (AUR).  This is a PHP
# script, and as such, you MUST pay great attention to the syntax.
# If your text contains any double-quotes ("), you MUST escape
# them with the backslash character (\).
#

include_once("translator.inc");
global $_t;

$_t["en"]["Click on the Home link above to log in."] = "Click on the Home link above to log in.";
# $_t["es"]["Click on the Home link above to log in."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Click on the Home link above to log in."] = "--> Traduction française ici. <--";
# $_t["de"]["Click on the Home link above to log in."] = "--> Deutsche Übersetzung hier. <--";

$_t["en"]["Your session has timed out.  You must log in again."] = "Your session has timed out.  You must log in again.";
# $_t["es"]["Your session has timed out.  You must log in again."] = "--> Traducción española aquí. <--";
# $_t["fr"]["Your session has timed out.  You must log in again."] = "--> Traduction française ici. <--";
# $_t["de"]["Your session has timed out.  You must log in again."] = "--> Deutsche Übersetzung hier. <--";

?>