<?php
# Russian (Русский) translation
# Translator: Sergej Pupykin <pupykin.s@gmail.com>

include_once("translator.inc");
global $_t;

$_t["ru"]["Proposal:"] = "Предложение:";

$_t["ru"]["No"] = "Против";

$_t["ru"]["Username does not exist."] = "Такого пользователя нет.";

$_t["ru"]["Next"] = "Далее";

$_t["ru"]["Add"] = "Добавить";

$_t["ru"]["Length must be at least 1."] = "Длина должна быть не меньше 1.";

$_t["ru"]["(defaults to 7 if empty)"] = "(7 если не указано иного)";

$_t["ru"]["Proposal cannot be empty."] = "Предложение не может быть пустым.";

$_t["ru"]["Vote ID not valid."] = "Идентификатор голосование неверный.";

$_t["ru"]["(empty if not applicable)"] = "(пусто если не применимо)";

$_t["ru"]["Voting is closed for this proposal."] = "Голосование закрыто.";

$_t["ru"]["New proposal submitted."] = "Новое предложение принято.";

$_t["ru"]["%s already has proposal running for them."] = "За %s уже идет голосование.";

$_t["ru"]["Length must be a number."] = "Длина должна быть числом.";

$_t["ru"]["You've already voted for this proposal."] = "Вы уже проголосовали.";

$_t["ru"]["Current Votes"] = "Сейчас голосов";

$_t["ru"]["You've already voted in this proposal."] = "Вы уже проголосовали.";

$_t["ru"]["You cannot vote in an proposal about you."] = "Нельзя голосовать за себя.";

$_t["ru"]["Abstain"] = "Воздерживаюсь";

$_t["ru"]["You are not allowed to access this area."] = "Нет доступа.";

$_t["ru"]["Length in days:"] = "Длительность в днях:";

$_t["ru"]["Back"] = "Назад";

$_t["ru"]["Submit a proposal to vote on."] = "Отправить предложение.";

$_t["ru"]["All Votes"] = "Всего";

$_t["ru"]["Could not retrieve proposal details."] = "Не получилось показать предложение.";

$_t["ru"]["Yes"] = "За";

$_t["ru"]["Applicant/TU:"] = "Кандидат/TU";

