<?
# Polish (Polski) translation
# Translator: Jaroslaw Swierczynski <swiergot@gmail.com>

include_once("translator.inc");
global $_t;

$_t["pl"]["Hi, this is worth reading!"] = "Witaj, warto to przeczytać!";
$_t["pl"]["You must supply a password."] = "Musisz podać hasło.";
$_t["pl"]["You must supply a username."] = "Musisz podać nazwę użytkownika.";
$_t["pl"]["Incorrect password for username %s."] = "Nieprawidłowe hasło dla użytkownika %s.";
$_t["pl"]["After that, this can be filled in with more meaningful text."] = "Potem można tu wstawić bardziej wyczerpujący tekst.";
$_t["pl"]["Your account has been suspended."] = "Twoje konto jest zablokowane.";
$_t["pl"]["Password:"] = "Hasło:";
$_t["pl"]["Username:"] = "Użytkownik:";
$_t["pl"]["It's more important to get the login functionality finished."] = "Ważniejsze jest dokończyć logowanie.";
$_t["pl"]["Currently logged in as: %h%s%h"] = "Obecnie zalogowany jako: %h%s%h";
$_t["pl"]["For now, it's just a place holder."] = "Narazie to tylko wypełnia przestrzeń.";
$_t["pl"]["This is where the intro text will go."] = "Tutaj będzie tekst powitalny.";
$_t["pl"]["Error trying to generate session id."] = "Błąd podczas generowania identyfikatora sesji.";
$_t["pl"]["Login"] = "Zaloguj się";
$_t["pl"]["Email Address:"] = "Adres e-mail:";
$_t["pl"]["You must supply an email address."] = "Musisz podać adres e-mail.";
$_t["pl"]["Incorrect password for email address, %s."] = "Nieprawidłowe hasło dla adresu %s.";
$_t["pl"]["Incorrect password for username, %s."] = "Nieprawidłowe hasło dla użytkownika %s.";
$_t["pl"]["Logged in as: %h%s%h"] = "Zalogowany jako: %h%s%h";
$_t["pl"]["Logged-in as: %h%s%h"] = "Zalogowany jako: %h%s%h";
$_t["pl"]["Error looking up username, %s."] = "Błąd podczas wyszukiwania użytkownika %s.";
$_t["pl"]["Welcome to the AUR! If you're a newcomer, you may want to read the %hGuidelines%h."] = "Witamy w AUR! Jeżeli jesteś tu po raz pierwszy, być może zechcesz przeczytać %hInstrukcję%h.";
$_t["pl"]["If you have feedback about the AUR, please leave it in %hFlyspray%h."] = "Jeżeli masz uwagi lub pomysły odnośnie AUR, %hFlyspray%h jest odpowiednim miejscem do ich pozostawienia.";
$_t["pl"]["Though we can't vouch for their contents, we provide a %hlist of user repositories%h for your convenience."] = "Dla Twojej wygody podajemy %hlistę repozytoriów użytkowników%h, ale uwaga - nie odpowiadamy za ich zawartość.";

?>
