<?php
# Ukrainian (Українська) translation
# Translator: sevenfourk <sevenfourk@gmail.com>

include_once("translator.inc");
global $_t;

$_t["uk"]["View this user's packages"] = "Дивитись пакунки цього користувача";

$_t["uk"]["It must be between %s and %s characters long"] = "Кількість символів повинна бути від %s до %s";

$_t["uk"]["Missing a required field."] = "Відсутній обов'язковий рядок.";

$_t["uk"]["The account, %h%s%h, has been successfully created."] = "Аккаунт, %h%s%h, було усспішно створено.";

$_t["uk"]["Error trying to modify account, %h%s%h: %s."] = "Помилка прри зміні аккаунту, %h%s%h: %s.";

$_t["uk"]["Your password must be at least %s characters."] = "Ваш пароль повинен бути довжиною не менш як %s символів.";

$_t["uk"]["The email address is invalid."] = "Адреса електронної пошти невірна.";

$_t["uk"]["Error trying to create account, %h%s%h: %s."] = "Помилка при створенні аккаунту, %h%s%h: %s.";

$_t["uk"]["The username, %h%s%h, is already in use."] = "Ім'я користувача %h%s%h вже існує.";

$_t["uk"]["Can contain only one period, underscore or hyphen."] = "Може містити тільки один період, підкреслення чи дефіс.";

$_t["uk"]["Account Type"] = "Тип Аккаунту";

$_t["uk"]["The account, %h%s%h, has been successfully modified."] = "Аккаунт %h%s%h було вдало змінено.";

$_t["uk"]["Account Suspended"] = "Аккаунт Підвішено";

$_t["uk"]["Start and end with a letter or number"] = "Початок та кінець з літери чи цифри";

$_t["uk"]["New Package Notify"] = "Повідомляти про нові пакунки";

$_t["uk"]["IRC Nick"] = "IRC Нік";

$_t["uk"]["Trusted user"] = "Довіренний користувач";

$_t["uk"]["No results matched your search criteria."] = "За вашим запитом нічого не знайдено.";

$_t["uk"]["Normal user"] = "Звичайний користувач";

$_t["uk"]["Never"] = "Ніколи";

$_t["uk"]["User"] = "Користувач";

$_t["uk"]["Active"] = "Активний";

$_t["uk"]["Last Voted"] = "Проголосував Останній";

$_t["uk"]["Real Name"] = "Справжнє Ім'я";

$_t["uk"]["Edit Account"] = "Редагувати Аккаунт";

$_t["uk"]["Password fields do not match."] = "Паролі не співпадають.";

$_t["uk"]["Status"] = "Статус";

$_t["uk"]["The username is invalid."] = "Ім'я користувача невірне.";

$_t["uk"]["Language"] = "Мова";

$_t["uk"]["A Trusted User cannot assign Developer status."] = "Довірений користувач не може встановлювати статус Розробника.";

$_t["uk"]["The address, %h%s%h, is already in use."] = "Адреса %h%s%h вже існує.";

$_t["uk"]["No more results to display."] = "Більше немає результатів.";

$_t["uk"]["Type"] = "Тип";

$_t["uk"]["Click on the Home link above to login."] = "Клікніть на посилання Home для того щоб зайти.";

$_t["uk"]["Re-type password"] = "Введіть пароль ще раз.";

$_t["uk"]["Language is not currently supported."] = "Мова не підтримується на даний момент.";

$_t["uk"]["Suspended"] = "Призупинено";

$_t["uk"]["Trusted User"] = "Довірений Користувач";

$_t["uk"]["Missing User ID"] = "Відсутній ідентифікатор користувача";

$_t["uk"]["Developer"] = "Розробник";

