<?php
# Ukrainian (Українська) translation
# Translator: sevenfourk <sevenfourk@gmail.com>

include_once("translator.inc");
global $_t;

$_t["uk"]["Reset"] = "Очистити";

$_t["uk"]["Username"] = "Ім'я користувача";

$_t["uk"]["Email Address"] = "Адреса електронної пошти";

$_t["uk"]["Less"] = "Назад";

$_t["uk"]["Clear"] = "Очистити";

$_t["uk"]["required"] = "необхідно";

$_t["uk"]["Update"] = "Поновити";

$_t["uk"]["Submit"] = "Надіслати";

$_t["uk"]["Password"] = "Пароль";

$_t["uk"]["Create"] = "Створити";

$_t["uk"]["More"] = "Далі";

