<?php
# Ukrainian (Українська) translation
# Translator: sevenfourk <sevenfourk@gmail.com>

include_once("translator.inc");
global $_t;

$_t["uk"]["Missing package ID."] = "Ідентифікатор пакету відсутній.";

$_t["uk"]["Invalid category ID."] = "Невірний ідентифікатор категорії.";

$_t["uk"]["Enter your comment below."] = "ВВедіть ваш коментар нижче.";

$_t["uk"]["You are not allowed to delete this comment."] = "У вас немає прав, щоб видалити цей коментар.";

$_t["uk"]["Missing comment ID."] = "Ідентифікатор коментару відсутній.";

$_t["uk"]["Package category updated."] = "Категорія пакунку поновлена.";

$_t["uk"]["You must be logged in before you can edit package information."] = "Ви повинні увійти у систему, щоб мати можливість редагувати інформацію про пакунок.";

$_t["uk"]["Comment has been deleted."] = "Коментар було видалено.";

$_t["uk"]["You've found a bug if you see this...."] = "Ви знайшли помилку, якщо ви бачите це....";

$_t["uk"]["Comment has been added."] = "Коментар додано.";

$_t["uk"]["Select new category"] = "Виберіть нову категорію.";

