<?php
# Ukrainian (Українська) translation
# Translator: sevenfourk <sevenfourk@gmail.com>

include_once("translator.inc");
global $_t;

$_t["uk"]["Category"] = "Категорія";

$_t["uk"]["Votes"] = "Голоси";

$_t["uk"]["Adopt Packages"] = "Прийняти Пакунки";

$_t["uk"]["Comments"] = "Коментарі";

$_t["uk"]["orphan"] = "Сироти";

$_t["uk"]["Out of Date"] = "Старий";

$_t["uk"]["First Submitted"] = "Вперше Надісланий";

$_t["uk"]["Tarball"] = "Архів";

$_t["uk"]["Voted"] = "Мій голос";

$_t["uk"]["Location"] = "Розташування";

$_t["uk"]["Delete comment"] = "Видалити коментар";

$_t["uk"]["Go"] = "Уперед";

$_t["uk"]["Unflag Out-of-date"] = "Зняти флаг Старий";

$_t["uk"]["Error retrieving package details."] = "Помилка при завантаженні інформації про пакунок.";

$_t["uk"]["Leave the password fields blank to keep your same password."] = "Залиште місце пдля паролей порожнім, щоб не міняти пароль.";

$_t["uk"]["Description"] = "Опис";

$_t["uk"]["unknown"] = "невідомо";

$_t["uk"]["This package has been flagged out of date."] = "Цьому пакунку було призначено флаг Старий";

$_t["uk"]["No New Comment Notification"] = "Немає нових оповіщень про коментарі";

$_t["uk"]["Dependencies"] = "Залежності";

$_t["uk"]["Disown Packages"] = "Кинути Пакунки";

$_t["uk"]["Required by"] = "Потребується пакунками";

$_t["uk"]["Package details could not be found."] = "Інформація про пакунок не знайдена.";

$_t["uk"]["You must log in to view user information."] = "Ви повинні увійти у систему, щоб дивитись дані користувача.";

$_t["uk"]["Package Details"] = "Інформація про Пакунок";

$_t["uk"]["Package Listing"] = "Список Пакунків";

$_t["uk"]["Files"] = "Файли";

$_t["uk"]["Name"] = "Ім'я";

$_t["uk"]["License"] = "Ліцензія";

$_t["uk"]["Last Updated"] = "Останній раз поновлений";

$_t["uk"]["Could not retrieve information for the specified user."] = "Не можливо отримати інмформацію про вказаного користувача.";

$_t["uk"]["UnNotify"] = "Не сповіщати";

$_t["uk"]["Showing results %s - %s of %s"] = "Результати %s - %s з %s";

$_t["uk"]["Vote"] = "Голос";

$_t["uk"]["Use this form to search existing accounts."] = "Використовуйте цю форму для пошуку існуючих аккаунтів.";

$_t["uk"]["Use this form to create an account."] = "Використовуйте цю форму, щоб створити аккаунт.";

$_t["uk"]["Un-Vote"] = "Забрати свій голос";

$_t["uk"]["change category"] = "змінити категорію";

$_t["uk"]["Use this form to update your account."] = "Використовуйте цю форму, для того щоб поновити свій аккаунт.";

$_t["uk"]["Delete Packages"] = "Видалити Пакунки";

$_t["uk"]["Maintainer"] = "Відповідальний";

$_t["uk"]["Add Comment"] = "Додати Коментар";

$_t["uk"]["Comment by: %h%s%h on %h%s%h"] = "Коментар: %h%s%h до %h%s%h";

$_t["uk"]["Flag Out-of-date"] = "Позначити як Старий";

$_t["uk"]["You are not allowed to access this area."] = "У вам немає прав доступу сюди.";

$_t["uk"]["Actions"] = "Дії";

$_t["uk"]["Sources"] = "Сирці";

$_t["uk"]["Toggle Notify"] = "Ввімк/Вимкн Оповіщення";

$_t["uk"]["Yes"] = "Так";

$_t["uk"]["Accounts"] = "Аккаунти";

$_t["uk"]["Notify"] = "Оповіщувати";

$_t["uk"]["You do not have permission to edit this account."] = "У вам немає прав, для того щоб редагувати цей аккаунт.";

$_t["uk"]["Home"] = "Home";

$_t["uk"]["New Comment Notification"] = "Оповіщення про новий коментар";

$_t["uk"]["Error retrieving package list."] = "Помилка при завантаженні списку пакунків.";

$_t["uk"]["No packages matched your search criteria."] = "За вашим запитом не знайдено пакунків.";

