<?php
# Ukrainian (Українська) translation
# Translator: sevenfourk <sevenfourk@gmail.com>

include_once("translator.inc");
global $_t;

$_t["uk"]["None of the selected packages could be deleted."] = "Жоден із вибраних пакунків не мможливо видалити.";

$_t["uk"]["Your votes have been removed from the selected packages."] = "Ваші голоси було видалено з вибраних пакунків.";

$_t["uk"]["You did not select any packages to un-vote for."] = "Ви не вибрали жодного пакунку щоб забрати голос.";

$_t["uk"]["The selected packages have been unflagged."] = "З вибраних пакунків було знято помітку";

$_t["uk"]["You did not select any packages to adopt."] = "Ви не вибрали жодного пакунку для прийняття.";

$_t["uk"]["You must be logged in before you can flag packages."] = "Ви повинні зайти , щоб ви могли позначати пакунки.";

$_t["uk"]["You must be logged in before you can get notifications on comments."] = "Ви повинні зайти, щоб мати можливість отримувати сповіщення про коментарі.";

$_t["uk"]["You must be logged in before you can vote for packages."] = "Ви повинні зайти, щоб мати змогу голосувати за пакунки.";

$_t["uk"]["The selected packages have been flagged out-of-date."] = "Для вибраних пакунків було призначено флаг Старий.";

$_t["uk"]["The selected packages have been deleted."] = "Вибрані пакунки були видалені.";

$_t["uk"]["You did not select any packages to vote for."] = "Ви не вибрали жодного пакунка для голосування.";

$_t["uk"]["You must be logged in before you can disown packages."] = "Ви повинні зайти, щоб кмити змогу кидати пакунки.";

$_t["uk"]["Error trying to retrieve package details."] = "Помилка при завантаженні інформації про пакунок.";

$_t["uk"]["The selected packages have been adopted."] = "Ви прийняли вибрані пакунки.";

$_t["uk"]["Your votes have been cast for the selected packages."] = "Ви проголосували за вибранііііі пакунки.";

$_t["uk"]["Packages"] = "Пакунки";

$_t["uk"]["You must be logged in before you can adopt packages."] = "Ви повинні зайти, щоб мати змогу приймати пакунки.";

$_t["uk"]["You did not select any packages to disown."] = "Ви не вибрали жодного пакунку щоб кинути.";

$_t["uk"]["You must be logged in before you can un-vote for packages."] = "Ви повинні зайти, щоб ви могли забирати свої голоси за пакунки.";

$_t["uk"]["You must be logged in before you can unflag packages."] = "Ви повинні зайти, щоб змати змогу знімати мітку з пакунків.";

$_t["uk"]["You did not select any packages to unflag."] = "Ви не вибрали жодного пакунку, щоб зняти мітку.";

$_t["uk"]["You did not select any packages to delete."] = "Ви не вибрали жодного пакунку для видалення.";

$_t["uk"]["You have been removed from the comment notification list for %s."] = "Вас було видалено із списку отримувачів оповіщень.";

$_t["uk"]["Couldn't add to notification list."] = "Не можливо додати до списку оповіщень.";

$_t["uk"]["You did not select any packages to flag."] = "Ви не вибрали жодного пакунку для мітки.";

$_t["uk"]["The selected packages have been disowned."] = "Ви позбулися вибраних пакунків.";

$_t["uk"]["You have been added to the comment notification list for %s."] = "Вас додали до списку отримувачів оповіщень.";

