<?php
# Ukrainian (Українська) translation
# Translator: sevenfourk <sevenfourk@gmail.com>

include_once("translator.inc");
global $_t;

$_t["uk"]["Error trying to unpack upload - PKGBUILD does not exist."] = "Помилка при розпакуванні завантаження - PKGBUILD не існує.";

$_t["uk"]["Unknown file format for uploaded file."] = "Невідомий формат завантаженого файлу.";

$_t["uk"]["Could not change directory to %s."] = "Не можливо змінити директорію до %s.";

$_t["uk"]["Invalid name: only lowercase letters are allowed."] = "Невірне ім'я: дозволені тільки малі літери.";

$_t["uk"]["Missing "] = "Відсутній";

$_t["uk"]["Could not create incoming directory: %s."] = "Неможливо створити каталог: %s.";

$_t["uk"]["Upload package file"] = "Завантажити файл пакунку";

$_t["uk"]["Missing build function in PKGBUILD."] = "Відсутня функція збирання у PKGBUILD.";

$_t["uk"]["Sorry, uploads are not permitted by this server."] = "Вибачте, завантаження не дозволені цим сервером.";

$_t["uk"]["Could not create directory %s."] = "Неможливо створити директорію %s.";

$_t["uk"]["Could not re-tar"] = "Неможливо перезапакувати";

$_t["uk"]["Upload"] = "Завантажити";

$_t["uk"]["You must create an account before you can upload packages."] = "Ви повинні створити аккаунт, щоб завантажувати пакунки.";

$_t["uk"]["Error - No file uploaded"] = "Помилка - Файл не було завантажено";

$_t["uk"]["Package URL is missing a protocol (ie. http:// ,ftp://)"] = "Не вказано протокол URL (напр. http:// , ftp://)";

$_t["uk"]["You are not allowed to overwrite the %h%s%h package."] = "Ви не маєте права перезаписувати пакунок %h%s%h.";

$_t["uk"]["Package Category"] = "Категорія Пакунку";

$_t["uk"]["Select Category"] = "Виберіть Категорію";

